<?php
/**
 * Jamroom Products module
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'products';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'create a new product';
$lang[2]  = 'create';
$lang[3]  = 'product title';
$lang[4]  = 'enter a title for this product - this will be used in the URL to view this product.';
$lang[5]  = 'product category';
$lang[6]  = 'Provide a Category for the product to group like items together.';
$lang[7]  = 'product description';
$lang[8]  = 'enter the description of this product.';
$lang[9]  = 'product images';
$lang[10] = 'select images that you would like to upload for this item (10 max)';
$lang[11] = 'select images to upload';
$lang[12] = 'Available';
$lang[13] = 'Leave empty if there is an unlimited quantity for sale. 0 means \'Sold Out\'. A user will not be able to purchase more items than there are for sale. ';
$lang[14] = 'Shipping and Handling';
$lang[15] = 'add a price for shipping and handling or use 0.00 for free shipping';
$lang[16] = 'update an existing product';
$lang[17] = 'save changes';
$lang[18] = 'you need to create at least one Product Category before creating a product';
$lang[19] = 'Products';
$lang[20] = 'create new category';
$lang[21] = 'category title';
$lang[22] = 'enter a title for this category';
$lang[23] = 'The entered category title already exists';
$lang[24] = 'create a new category';
$lang[25] = 'update an existing category';
$lang[26] = 'Product Categories';
$lang[27] = 'no categories found';
$lang[28] = 'cancel';
$lang[29] = 'update';
$lang[30] = 'delete';
$lang[31] = 'Delete this category?';
$lang[32] = 'Created a new Product';
$lang[33] = 'Updated a Product';
$lang[34] = 'Field Type';
$lang[35] = 'Select the type of field to to added to this category. If \'select\', add in the options (one per line) in the Field Options below.';
$lang[36] = 'Field Label';
$lang[37] = 'Enter the label that will show next to this field, eg. \'color\', \'size\'.';
$lang[38] = 'Field Options';
$lang[39] = 'If this is a \'select\' field, enter the options here, one per line. Otherwise, if required, enter a \'default\' field value.';
$lang[40] = 'Category Field';
$lang[41] = 'Sold Out';
$lang[42] = 'click to view images';
$lang[43] = 'items';
$lang[44] = 'shipping';
$lang[45] = 'contact seller';
$lang[46] = 'Please select a product category';
