<?php
/**
 * Jamroom jrNovaLight skin
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 Nova Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1] = 'Home';
$lang[2] = 'anlegen';
$lang[3] = 'Konto';
$lang[4] = 'Profil';
$lang[5] = 'ausloggen';
$lang[6] = 'einloggen';
$lang[7] = 'Willkommen zu';
$lang[8] = 'Seite';
$lang[9] = 'Neuigkeiten';
$lang[10] = 'Blog';
$lang[11] = 'Neueste';
$lang[12] = 'Künstler';
$lang[13] = 'Lieder';
$lang[14] = 'Videos';
$lang[15] = 'YouTube';
$lang[16] = 'Admin';
$lang[17] = 'Dashboard';
$lang[18] = 'Seiten';
$lang[19] = 'Ereignisse';
$lang[20] = 'Menü';
$lang[21] = 'Empfohlene';
$lang[22] = 'alle';
$lang[23] = 'alle sehen';
$lang[24] = 'suchen';
$lang[25] = 'Bild ändern';
$lang[26] = 'AKP';
$lang[27] = 'Charts';
$lang[28] = 'Lied';
$lang[29] = 'Video';
$lang[30] = 'Konzerte';
$lang[31] = 'top';
$lang[32] = 'wöchentlich';
$lang[33] = 'monatlich';
$lang[34] = 'jährlich';
$lang[35] = 'Community';
$lang[36] = 'neueste Beiträge';
$lang[37] = 'Partner';
$lang[38] = 'Benutzer';
$lang[39] = 'online';
$lang[40] = 'Karte';
$lang[41] = 'mehr';
$lang[42] = 'Statistiken';
$lang[43] = 'Radio';
$lang[44] = 'TV';
$lang[45] = 'Einstellungen';
$lang[46] = 'verschoben';
$lang[47] = 'Position';
$lang[48] = 'nach Name';
$lang[49] = 'mal gespielt';
$lang[50] = 'nach gespielter Anzahl';
$lang[51] = 'demnächst';
$lang[52] = 'Archive';
$lang[53] = 'Beitrag';
$lang[54] = 'nach Bewertung';
$lang[55] = 'Profile';
$lang[56] = 'Master';
$lang[57] = 'Admins';
$lang[58] = 'Mitglieder';
$lang[59] = 'Besucher';
$lang[60] = 'gesamt';
$lang[61] = 'SoundCloud';
$lang[62] = 'YouTube';
$lang[63] = 'Vimeo';
$lang[64] = 'Oberfläche';
$lang[65] = 'System Werkzeuge';
$lang[66] = 'Geschäftsbedingungen';
$lang[67] = 'Datenschutzrichtlinie';
$lang[68] = 'Uns kontaktieren';
$lang[69] = 'Betreff';
$lang[70] = 'Nachricht';
$lang[71] = 'Ihr könnt uns über unten stehende Adresse, E-Mail-Adresse oder Telefonnummer kontaktieren.';
$lang[72] = 'Einstellungen ändern';
$lang[73] = 'Bitte die zu sendende Nachricht eingeben';
$lang[74] = ' und wir werden uns sobald wie möglich bei dir melden.';
$lang[75] = 'Nachricht senden';
$lang[76] = 'Du hast deine Kontaktinformationen nicht zu den Oberflächeneinstellungen hinzugefügt! Ändere die Kontakteinstellungen, indem du auf den Zahnradknopf rechts klickst';
$lang[77] = 'Entschuldigung! Wir haben unsere Informationen diesem Bereich noch nicht hinzugefügt.';
$lang[78] = 'Aktivitätsprotokoll';
$lang[79] = 'Cache zurücksetzen';
$lang[80] = 'Integritätsprüfung';
$lang[81] = 'verbotene Elemente';
$lang[82] = 'Oberflächen Menu Editor';
$lang[83] = 'Sitemap erzeugen';
$lang[84] = 'Systemprüfung';
$lang[85] = 'abbrechen';
$lang[86] = 'über';
$lang[87] = 'Followers';
$lang[88] = 'Ansichten';
$lang[89] = 'anmelden';
$lang[90] = 'Kategorien';
$lang[91] = 'Entwickler Werkzeuge';
$lang[92] = 'Bilder Cache zurücksetzen';
$lang[93] = 'Blogs';
$lang[94] = 'Einflüsse';
$lang[95] = 'vor kurzem bewertet';
$lang[96] = 'Quota Browser';
$lang[97] = 'Benutzerkonten';
$lang[98] = 'Aktivitätsanzeige';
$lang[99] = 'Profil Browser';
$lang[100] = 'Wer ist Online';
$lang[101] = 'Benutzer';
$lang[102] = 'Oberflächeneinstellungen';
$lang[103] = 'Beiträge';
$lang[104] = 'nach Ort';
$lang[105] = 'erzeugt';
$lang[106] = 'System-Updates';
$lang[107] = 'Debug-Protokolle';
$lang[108] = 'PHP-Fehlerprotokolle';
$lang[109] = 'Haut Hinweise';
$lang[110] = 'Haut-Stil';
$lang[111] = 'Hautbilder';
$lang[112] = 'Haut-Vorlagen';
$lang[113] = 'Haut-Sprache';
$lang[114] = 'Bemerkungen';
$lang[115] = 'Sorry, no Benutzer Online!';
$lang[116] = 'Können Sie helfen diese Site';
$lang[117] = 'Aktiv Mit dem Login!';
$lang[118] = 'ODER';
