<?php
/**
 * Jamroom jrNovaLight skin
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 Nova Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1] = 'accueill';
$lang[2] = 'créer';
$lang[3] = 'compte';
$lang[4] = 'profile';
$lang[5] = 'déconnexion';
$lang[6] = 'accés a votre compte';
$lang[7] = 'bienvenue sur';
$lang[8] = 'site';
$lang[9] = 'Actualités';
$lang[10] = 'Blog';
$lang[11] = 'le plus récent';
$lang[12] = 'Artistes';
$lang[13] = 'mots';
$lang[14] = 'Vidéos';
$lang[15] = 'YouTube';
$lang[16] = 'administrateur';
$lang[17] = 'tableau de bord';
$lang[18] = 'pages';
$lang[19] = 'événements';
$lang[20] = 'menu';
$lang[21] = 'en vedette';
$lang[22] = 'tout';
$lang[23] = 'voir tous';
$lang[24] = 'recherche';
$lang[25] = 'Changer Image';
$lang[26] = 'PCA';
$lang[27] = 'graphiques';
$lang[28] = 'Mot';
$lang[29] = 'Video';
$lang[30] = 'Concerts';
$lang[31] = 'en haut';
$lang[32] = 'Chaque Semaine';
$lang[33] = 'Chaque Mois';
$lang[34] = 'Chaque Année';
$lang[35] = 'Communité';
$lang[36] = 'derniers articles';
$lang[37] = 'Nos Commanditaires';
$lang[38] = 'utilisateurs';
$lang[39] = 'en ligne';
$lang[40] = 'panier';
$lang[41] = 'plus';
$lang[42] = 'statistiques';
$lang[43] = 'radio';
$lang[44] = 'TV';
$lang[45] = 'Paramètres';
$lang[46] = 'déplacé';
$lang[47] = 'position';
$lang[48] = 'par nom';
$lang[49] = 'jeux';
$lang[50] = 'par nombre de lectures';
$lang[51] = 'prochain';
$lang[52] = 'Archives';
$lang[53] = 'Article';
$lang[54] = 'par notes';
$lang[55] = 'profils';
$lang[56] = 'maître';
$lang[57] = 'administrateurs';
$lang[58] = 'Membres';
$lang[59] = 'visiteurs';
$lang[60] = 'total';
$lang[61] = 'SoundCloud';
$lang[62] = 'YouTube';
$lang[63] = 'Vimeo';
$lang[64] = 'Skin';
$lang[65] = 'outils système';
$lang[66] = 'Conditions de Service';
$lang[67] = 'Politique de Confidentialité';
$lang[68] = 'Contactez-nous';
$lang[69] = 'sujet';
$lang[70] = 'message';
$lang[71] = 'Vous pouvez nous contacter en utilisant l\'adresse, adresse e-mail ou numéro de téléphone ci-dessous.';
$lang[72] = 'Modifier les Paramètres';
$lang[73] = 'S\'il vous plaît entrez le message que vous souhaitez envoyer';
$lang[74] = ' et nous reviendrons vers vous dès que possible.';
$lang[75] = 'Envoyer Message';
$lang[76] = 'Vous n\'avez pas ajouté vos coordonnées dans les paramètres de l\'apparence! Modifiez les paramètres de contact en cliquant sur le bouton en forme de rouage vers la droite.';
$lang[77] = 'Désolé! Nous n\'avons pas encore ajouté notre information pour cette section.';
$lang[78] = 'Journaux d\'activité';
$lang[79] = 'Vider le cache';
$lang[80] = 'Vérifier l\'intégrité';
$lang[81] = 'Articles Interdits';
$lang[82] = 'Menu de l\'éditeur d\'apparence';
$lang[83] = 'Créez Plan du site';
$lang[84] = 'Vérification du Système';
$lang[85] = 'Annuler';
$lang[86] = 'À propos de';
$lang[87] = 'Abonnements';
$lang[88] = 'Vues';
$lang[89] = 'Souscrire';
$lang[90] = 'catégories';
$lang[91] = 'Outils de Développement';
$lang[92] = 'Vider le cache de l\'image';
$lang[93] = 'Blogs';
$lang[94] = 'Influences';
$lang[95] = 'Noté récemment';
$lang[96] = 'Quota de Navigateur Internet';
$lang[96] = 'Navigateur de Quota';
$lang[97] = 'Comptes d\'utilisateurs';
$lang[98] = 'flux d\'activité';
$lang[99] = 'profil Navigateur';
$lang[100] = 'Qui est en ligne';
$lang[101] = 'Utilisateurs';
$lang[102] = 'Paramètres de l\'apparence';
$lang[103] = 'Articles';
$lang[104] = 'par emplacement';
$lang[105] = 'Créer';
$lang[106] = 'Mises à jour système';
$lang[107] = 'Les journaux de débogage';
$lang[108] = 'Journaux PHP d\'erreur';
$lang[109] = 'Notes peau';
$lang[110] = 'Style de la peau';
$lang[111] = 'Images de la peau';
$lang[112] = 'Modèles de la peau';
$lang[113] = 'Langue de la peau';
$lang[114] = 'Commentaires';
$lang[115] = 'Désolé, aucun Utilisateurs en ligne!';
$lang[116] = 'Vous pouvez aider à faire de ce site';
$lang[117] = 'Actif en vous connectant!';
$lang[118] = 'OU';
