<?php
/**
 * Jamroom jrNovaLight skin
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 Nova Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1] = 'Start';
$lang[2] = 'maak';
$lang[3] = 'account';
$lang[4] = 'profiel';
$lang[5] = 'afmelden';
$lang[6] = 'inloggen';
$lang[7] = 'welkom bij';
$lang[8] = 'site';
$lang[9] = 'Nieuws';
$lang[10] = 'Blog';
$lang[11] = 'nieuwste';
$lang[12] = 'Artiesten';
$lang[13] = 'Liedjes';
$lang[14] = 'Videos';
$lang[15] = 'YouTube';
$lang[16] = 'admin';
$lang[17] = 'Dashboard';
$lang[18] = 'pagina\'s';
$lang[19] = 'Evenementen';
$lang[20] = 'menu';
$lang[21] = 'featured';
$lang[22] = 'alles';
$lang[23] = 'bekijk alles';
$lang[24] = 'zoek';
$lang[25] = 'Verander foto';
$lang[26] = 'ACP';
$lang[27] = 'Hitlijst';
$lang[28] = 'Lied';
$lang[29] = 'Video';
$lang[30] = 'Concerten';
$lang[31] = 'top';
$lang[32] = 'Wekelijks';
$lang[33] = 'Maandelijks';
$lang[34] = 'Jaarlijks';
$lang[35] = 'Groep';
$lang[36] = 'Laatste Artikelen';
$lang[37] = 'Leden aannemen';
$lang[38] = 'Leden';
$lang[39] = 'online';
$lang[40] = 'winkelwagen';
$lang[41] = 'meer';
$lang[42] = 'statistieken';
$lang[43] = 'radio';
$lang[44] = 'TV';
$lang[45] = 'instellingen';
$lang[46] = 'verplaatst';
$lang[47] = 'positie';
$lang[48] = 'bij naam';
$lang[49] = 'speelt';
$lang[50] = 'bij speelt';
$lang[51] = 'volgende';
$lang[52] = 'Archieven';
$lang[53] = 'Artikel';
$lang[54] = 'bij cijfers';
$lang[55] = 'profielen';
$lang[56] = 'meester';
$lang[57] = 'admins';
$lang[58] = 'Leden';
$lang[59] = 'bezoekers';
$lang[60] = 'totaal';
$lang[61] = 'SoundCloud';
$lang[62] = 'YouTube';
$lang[63] = 'Vimeo';
$lang[64] = 'Skin';
$lang[65] = 'Systeem gereedschap';
$lang[66] = 'Voorwaarden';
$lang[67] = 'Privé beleid';
$lang[68] = 'Contact Ons';
$lang[69] = 'onderwerp';
$lang[70] = 'bericht';
$lang[71] = 'Je kunt ons bereiken op het adres, email addres of telefoonnummer hieronder';
$lang[72] = 'verander instellingen';
$lang[73] = 'Schrijf hier het bericht dat je wilt sturen';
$lang[74] = ' en we beantwoorden je zo snel mogelijk';
$lang[75] = 'Verstuur bericht';
$lang[76] = 'Je hebt niet je contactinformatie vermeld in de skin instellingen! Verander de contactinstellingen door op de \'gear\' button rechts te drukken.';
$lang[77] = 'Sorry! We hebben je info in deze sectie nog niet bijgewerkt.';
$lang[78] = 'Aktiviteiten Logs';
$lang[79] = 'Reset Cache';
$lang[80] = 'Integriteit Check';
$lang[81] = 'Gebande stukken';
$lang[82] = 'Skin Menu Wijziger';
$lang[83] = 'Maak Sitemap';
$lang[84] = 'Systeem Check';
$lang[85] = 'Annuleren';
$lang[86] = 'Over';
$lang[87] = 'Volgers';
$lang[88] = 'bekeken';
$lang[89] = 'Aanmelden';
$lang[90] = 'categoriën';
$lang[91] = 'Developer Gereedschap';
$lang[92] = 'Herstel Image Cache';
$lang[93] = 'Blogs';
$lang[94] = 'Invloeden';
$lang[95] = 'Recent een cijfer gegeven';
$lang[96] = 'Quota Browser';
$lang[97] = 'Gebruikers Accounts';
$lang[98] = 'activiteiten feed';
$lang[99] = 'Profiel Browser';
$lang[100] = 'Wie is er online';
$lang[101] = 'Gebruikers';
$lang[102] = 'Skin instellingen';
$lang[103] = 'Artikels';
$lang[104] = 'bij lokatie';
$lang[105] = 'Aangemaakt';
$lang[106] = 'System Updates';
$lang[107] = 'Debug Logs';
$lang[108] = 'PHP Error Logs';
$lang[109] = 'huid Opmerkingen';
$lang[110] = 'Skin Style';
$lang[111] = 'huid Afbeeldingen';
$lang[112] = 'huid Templates';
$lang[113] = 'Skin Taal';
$lang[114] = 'Comments';
$lang[115] = 'Sorry, Geen gebruikers online!';
$lang[116] = 'U kunnen helpen om deze site';
$lang[117] = 'Actief door in te loggen!';
$lang[118] = 'OF';
