<?php
/**
 * Jamroom Users module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION!
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]   = 'user login';
$lang[2]   = 'please enter your user name and password to login';
$lang[3]   = 'login';
$lang[4]   = 'user name';
$lang[5]   = 'please enter your user name';
$lang[6]   = 'you forgot to enter your user name';
$lang[7]   = 'password';
$lang[8]   = 'please enter your password';
$lang[9]   = 'you forgot to enter your password';
$lang[10]  = 'You have entered an invalid user name or password - please try again';
$lang[11]  = 'The system is currently down for maintenance - please try again shortly';
$lang[12]  = 'Your account has logged in from too many different locations and has been temporarily locked. Please contact the system administrator for assistance with your account';
$lang[13]  = 'remember login';
$lang[14]  = 'check this option to remember your login information for next time';
$lang[15]  = 'update account info';
$lang[16]  = 'update existing account information';
$lang[17]  = 'save changes';
$lang[18]  = 'email address';
$lang[19]  = 'please enter a valid email address or user name to log into the system.';
$lang[20]  = 'new password';
$lang[21]  = 'please enter a strong password';
$lang[22]  = 'repeat new password';
$lang[23]  = 'repeat the password you entered to be sure there are no typos';
$lang[24]  = 'maintenance login';
$lang[25]  = 'if checked, this user will be allowed to log into the system when the system is in maintenance mode';
$lang[26]  = 'Invalid Login or Password - please try again';
$lang[27]  = 'Your account is pending validation - please check your email for the activation link.';
$lang[28]  = 'Click here to have your Activation Email resent to you';
$lang[29]  = 'Your account is not currently active - please contact the System Administrator for assistance';
$lang[30]  = 'Only admins can login while the system is in maintenance mode';
$lang[31]  = 'Create Account';
$lang[32]  = 'repeat password';
$lang[33]  = 'That User Name is already being used - did you already create an account previously?';
$lang[34]  = 'That Email Address is already being used - did you already create an account previously?';
$lang[35]  = 'The passwords you have entered do not match';
$lang[36]  = 'An error was encountered saving the account information - please try again';
$lang[37]  = "You're almost done - we have just sent you an activation email!<br><br>Please check your email account for instructions on validating your account.";
$lang[38]  = '<b>Invalid Activation Key!</b><br><br>Make sure you are entering the full URL from the activation email - some email clients will cut the URL off.';
$lang[39]  = '<p>Your account has been activated, and you have been logged in.<br><br>Thank you for signing up!</p>';
$lang[40]  = 'Login';
$lang[41]  = 'Forgot Login?';
$lang[42]  = 'Account';
$lang[43]  = 'The account settings were successfully saved';
$lang[44]  = 'Forgot Login';
$lang[45]  = 'create account';
$lang[46]  = 'submit address or user name';
$lang[47]  = 'enter the email address you used to signup with';
$lang[48]  = 'An account with that email address or user name was not found - please try again';
$lang[49]  = 'Please check your email account for further instructions on accessing your account';
$lang[50]  = 'Set a new Password';
$lang[51]  = 'set new password and login';
$lang[52]  = 'Invalid Password Reset token - please check your password reset email for the proper reset URL';
$lang[53]  = 'photo';
$lang[54]  = 'view your profile';
$lang[55]  = 'The User Name you have entered is not allowed - please try another';
$lang[56]  = 'Your account has already been validated, and you should be able to log in now';
$lang[57]  = 'The Email Address that your account is tied to - please ensure this is a valid email address.  If you forget your password, this is the email address where you can receive instructions on resetting your password.';
$lang[58]  = 'Signups are currently disabled - please try again shortly.';
$lang[59]  = 'Account Type';
$lang[60]  = 'Select the Type of Account you would like to sign up for.';
$lang[61]  = 'Invalid Signup Account Type - please ensure you are choosing a valid Signup Account Type';
$lang[62]  = 'language';
$lang[63]  = 'Select the language you would like to use throughout the site';
$lang[64]  = 'Notifications';
$lang[65]  = 'Do Not Notify';
$lang[66]  = 'Send Email';
$lang[67]  = 'Send Private Note';
$lang[68]  = 'Please enter an email address - you will not be able to retrieve your account information if you need it!';
$lang[69]  = 'This is a quick email to let you know that your email address on your';
$lang[70]  = 'account has been changed to';
$lang[71]  = 'If you did NOT change this in your account, please login ASAP and change your email address back, and let us know.';
$lang[72]  = 'Your email address on your account has been changed';
$lang[73]  = 'A new';
$lang[74]  = 'account has been created for you!';
$lang[75]  = 'username';
$lang[76]  = 'Log in to the system here';
$lang[77]  = 'Please CHANGE YOUR PASSWORD once you are logged in.';
$lang[78]  = 'We look forward to seeing you online!';
$lang[79]  = 'your new';
$lang[80]  = 'account';
$lang[81]  = 'We\'ve received a password reset request for this email address.  If you requested your password to be reset, please click on the following link, or cut and paste it into your browser window';
$lang[82]  = 'This will allow you to set a new password for your account. If you did not request this password reset request, you can ignore this email and the request will expire.';
$lang[83]  = 'password reset';
$lang[84]  = 'Thank you for signing up for a';
$lang[85]  = 'account!';
$lang[86]  = 'You are one step away from joining our community - simply click on the following link to activate your account';
$lang[87]  = 'If you have any questions, or have any issues validating your account, please don\'t hesitate to contact us.';
$lang[88]  = 'account validation';
$lang[89]  = 'invalid user id - please try again';
$lang[90]  = 'human check';
$lang[91]  = 'check this to let us know you are human, and not a spam bot.';
$lang[92]  = 'You forgot to check the &quot;human check&quot; checkbox - if you are not a spam bot, make sure it is checked.';
$lang[93]  = 'Upload a unique User Photo that will be used in your User Account. Note that this photo is different than the photo used in your Profile, which can be set in the &quot;Profile&quot; tab.';
$lang[94]  = 'All notification emails have been disabled';
$lang[95]  = 'All notifications are currently disabled - you will not receive any notifications!';
$lang[96]  = 'The email address you entered is already being used by another account';
$lang[97]  = 'If you would prefer to no longer receive event notifications, you can adjust';
$lang[98]  = 'your notification preferences in your User Account:';
$lang[99]  = 'Or you can disable all notifications for all events:';
$lang[100] = 'The User Name you have entered is already being used by another account';
$lang[101] = 'online';
$lang[102] = 'offline';
$lang[103] = 'email address or user name';
$lang[104] = 'enter the email address you used to signup, or your user name to start the password reset process';
$lang[105] = "Your account has been successfully created!<br>An Admin has been notified to approve your account - you will be notified by email when you're all set.<br>Thanks for signing up!";
$lang[106] = 'Oops - set my notification preference back to the way they were';
$lang[107] = 'You are no longer blocking all notifications';
$lang[108] = 'You must be logged in before you can continue';
$lang[109] = 'This site is private and only visible to logged in users.';
$lang[110] = 'Click Here to Log In';
$lang[111] = 'Click Here to Create an Account';
$lang[112] = 'You must enter your <strong>existing password</strong> to continue';
$lang[113] = 'continue';
$lang[114] = 'Login box will show here for non-logged in users';
$lang[115] = 'Form submitted successfully - Thank you!';
$lang[116] = 'account settings';
$lang[117] = 'log out';
$lang[118] = 'Unsubscribe from all email notifications';
$lang[119] = 'Unsubscribe';
$lang[120] = 'Check this option to be removed from all Notifications.';
$lang[121] = 'Your Email Address will be removed from all future notifications';
$lang[122] = 'disable all notifications';
$lang[123] = 'An email with an unsubscribe confirm link has been sent to ';
$lang[124] = 'Please open that email and confirm you wish to unsubscribe or login and change your notifications from the notifications tab.';
