<?php
/**
 * Jamroom Merchandise module
 *
 * copyright 2003 - 2016
 * by The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'products';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'create a new product';
$lang[2]  = 'create';
$lang[3]  = 'product title';
$lang[4]  = 'enter a title for this product - this will be used in the URL to view this product.';
$lang[5]  = 'product content';
$lang[6]  = 'enter the content for this product.';
$lang[7]  = 'An error was encountered saving the product - please try again.';
$lang[8]  = 'The new product was successfully created!';
$lang[9]  = 'Invalid product_id - please try again';
$lang[10] = 'update an existing product';
$lang[11] = 'save changes';
$lang[12] = 'The product update was successfully saved.';
$lang[13] = 'product category';
$lang[14] = 'Provide a Category for the product to group like items together.';
$lang[15] = 'Your comment was successfully posted';
$lang[16] = 'Send';
$lang[17] = 'view product';
$lang[18] = 'Created a new Product';
$lang[19] = 'Products';
$lang[20] = 'home';
$lang[21] = 'Category';
$lang[22] = 'You forgot to enter a comment!';
$lang[23] = 'Your comment was successfully posted';
$lang[24] = 'failed to update the database with the comment.';
$lang[25] = 'product images';
$lang[26] = 'select images that you would like to upload for this item';
$lang[27] = 'select images to upload';
$lang[28] = 'delete';
$lang[29] = 'click to view images';
$lang[30] = 'new sale (store)';
$lang[31] = 'new order message (store)';
$lang[32] = 'When you make a sale of merchandise that needs to be shipped, how do you want to be notified?';
$lang[33] = 'When a customer sends you a message about a specific order, how do you want to be notified?';
$lang[34] = 'Product Sales';
$lang[35] = 'settings';
$lang[36] = 'save changes';
$lang[37] = 'The store settings have been successfully saved';
$lang[38] = 'first customer message';
$lang[39] = 'enter the message you would like sent to a customer when they purchase an item - this should include information on shipping, as well as any specual instructions the buyer might need to complete the transaction.';
$lang[40] = 'store details';
$lang[41] = 'Enter details about your store - i.e. Where you are located, where items ship from, What your shipping options are, etc...';
$lang[42] = 'Quantity Available';
$lang[43] = 'Leave empty if there is an unlimited quantity for sale. 0 means \'Sold Out\'. A user will not be able to purchase more items than there are for sale. ';
$lang[44] = 'Items Ship from';
$lang[45] = 'Enter the location where your stores shipping is calculated from for domestic and international shipping of items.';
$lang[46] = 'Domestic Shipping';
$lang[47] = 'add a price for domestic shipping, use 0.00 for free shipping';
$lang[48] = 'International Shipping';
$lang[49] = 'add a price for international shipping, use 0.00 for free shipping';
$lang[50] = 'Sold Out';
$lang[51] = 'There is a new message from %1 on a store order:';
$lang[52] = 'Reply here:';
$lang[53] = 'New message from %1 on order: %2';
$lang[54] = 'Congratulations %1,';
$lang[55] = 'You have made a sale of some merchandise, please communicate with the buyer to get the goods sent out to them.';
$lang[56] = 'Communicate with your customer here:';
$lang[57] = 'All Sales';
$lang[58] = 'Details';
$lang[59] = 'Communication';
$lang[60] = 'All Purchases';
$lang[61] = 'On Hold';
$lang[62] = 'Processing';
$lang[63] = 'Posted';
$lang[64] = 'Delivered';
$lang[65] = 'Canceled';
$lang[66] = 'Who the seller is:';
$lang[67] = 'Profile Name';
$lang[68] = 'Store Country';
$lang[69] = "What I'm getting from them:";
$lang[70] = 'Name';
$lang[71] = 'Qty';
$lang[72] = 'Bundle';
$lang[73] = '(not part of a bundle)';
$lang[74] = 'Where it is shipping from:';
$lang[75] = 'Status of the order:';
$lang[76] = 'Status:';
$lang[77] = 'That my address is correct:';
$lang[78] = 'Purchases list';
$lang[79] = 'Price';
$lang[80] = 'Date';
$lang[81] = 'Seller';
$lang[82] = 'Details';
$lang[83] = 'Items';
$lang[84] = 'Status';
$lang[85] = 'Messages';
$lang[86] = 'Last Message From';
$lang[87] = 'Status was successfully updated';
$lang[88] = 'Order Status:';
$lang[89] = 'Comments:';
$lang[90] = 'Customer First Name';
$lang[91] = 'Customer Last Name';
$lang[92] = 'Customer ID';
$lang[93] = 'Customer Postal Code';
$lang[94] = 'Purchase Date';
$lang[95] = 'Email';
$lang[96] = 'Company';
$lang[97] = 'Address1';
$lang[98] = 'Address2';
$lang[99] = 'City';
$lang[100] = 'Country';
$lang[101] = 'Order Total';
$lang[102] = 'Product Total';
$lang[103] = 'Shipping First Name';
$lang[104] = 'Shipping Last Name';
$lang[105] = 'Ship to Company Name';
$lang[106] = 'Shipping Address1';
$lang[107] = 'Shipping Address2';
$lang[108] = 'Shipping Country';
$lang[109] = 'Country';
$lang[110] = 'Shipping postal Code';
$lang[111] = 'Shipping Total';
$lang[112] = 'Shipping Tax Total';
$lang[113] = '%1 Fees';
$lang[114] = 'Order Items';
$lang[115] = 'Shipping Label';
$lang[116] = 'Purchaser';
$lang[117] = 'Gross';
$lang[118] = 'Fees';
$lang[119] = 'Net';
$lang[120] = 'extra';
$lang[121] = 'Notes';
$lang[122] = 'Last';
$lang[123] = 'Order Communication:';
$lang[124] = 'Send a message:';
$lang[125] = 'Order Details:';
$lang[126] = 'Updated a Product';

