<?php
/**
 * Jamroom OneAll Social module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'social network login';
$lang[2]  = 'social network signup';
$lang[3]  = 'social login';
$lang[4]  = 'Log in or Sign Up using any of the Social Networks listed';
$lang[5]  = 'Networks';
$lang[6]  = 'Link your Activity to Social Networks';
$lang[7]  = 'available networks';
$lang[8]  = 'Select the external social networks you would like to link to your account - note that you must already have an account on the linked social network, and have linked it to your account in order to link your activity stream.';
$lang[9]  = 'This section is currently being set up - please try again later';
$lang[10] = 'active networks';
$lang[11] = 'Select your Social Networks you would like to link to your Activity Stream.';
$lang[12] = 'Your network settings have been saved';
$lang[13] = 'Where you share your Activity';
$lang[14] = 'share activity with';
$lang[15] = 'Select the networks you would like to share this activity with.';
$lang[16] = 'Your new %1 password';
$lang[17] = 'Thank you for creating your account!  Since you created your';
$lang[18] = "account by linking up with %1, we've created you a";
$lang[19] = 'new temporary password that you can use to log into the';
$lang[20] = 'system without relying on %1 (although you can always';
$lang[21] = 'log in using %1 too):';
$lang[22] = 'Please change your password as soon as you can:';
$lang[23] = 'We look forward to seeing you online!';
$lang[24] = 'user:';
$lang[25] = 'pass:';
$lang[26] = 'Your preferred name is already being used - please enter a different User Name';
$lang[27] = 'The email address is already in use on this system - did you forget your login?';
$lang[28] = 'We were unable to get your email address from the provider due to privacy settings on your account<br>Please create your account here or try a different provider.';
$lang[29] = 'Please enter a new password for your account';
$lang[30] = 'We were unable to retrieve some required information about your account!<br>Please enter values for the highlighted fields below - <br>without these values your account will not function correctly.';
$lang[31] = 'Your email address is already being used in the system - please log in and view your Account Setting -> Networks section to link up your account.';
$lang[32] = 'Continue';
