<?php
/**
 * Jamroom Item Ratings module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Rate';
$lang[2]  = 'Average:';
$lang[3]  = 'Votes';
$lang[4]  = 'User not logged in or not allowed to rate';
$lang[5]  = 'Invalid or banned IP address';
$lang[6]  = 'Module being rated not enabled or invalid';
$lang[7]  = 'Item being rated does not exist';
$lang[8]  = 'Invalid rating value';
$lang[9]  = 'You have already rated this item';
$lang[10] = 'System error when rating the item';
$lang[11] = 'Rated with a';
$lang[12] = 'Item rated';
$lang[13] = 'If one of your items is rated, would you like to be notified?';
$lang[14] = 'Visitor';
$lang[15] = 'Activity Update';
$lang[16] = 'Rated';
$lang[17] = 'a';
