<?php
/**
 * Jamroom Group Mailer module
 *
 * copyright 2003 - 2016
 * by The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 jrGroupMailer module - language strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Group email';
$lang[2]  = 'Please select recipients';
$lang[3]  = 'You have been successfully unsubscribed from group emails.';
$lang[4]  = 'Would you like to receive emails from group admins?';
$lang[5]  = 'Mail Members';
$lang[6]  = 'Save As New Template';
$lang[7]  = 'Browse Templates';
$lang[8]  = 'Compose Group Email';
$lang[9]  = 'Send Group Email';
$lang[10] = 'Send this email to the selected group members?';
$lang[11] = 'Group Email templates';
$lang[12] = 'select as a starting point';
$lang[13] = 'Email Subject';
$lang[14] = 'should be unique';
$lang[15] = 'Enter the group email subject (required).';
$lang[16] = 'Email Content';
$lang[17] = 'Enter the group email content (required)';
$lang[18] = 'Test: &nbsp; Send Only to';
$lang[19] = 'Select Recipient Group';
$lang[20] = 'Select the group you would like to send this email to.';
$lang[21] = 'A TEST group email was sent to';
$lang[22] = 'The group email has been submitted for delivery!';
$lang[23] = 'The template was successfully saved';
$lang[24] = 'The group email was successfully saved';
$lang[25] = 'New Group Email from this Template';
$lang[26] = 'Save Changes';
$lang[27] = 'Template Title';
$lang[28] = 'This is the name of the Template as it will appear in the Template Browser';
$lang[29] = 'Template Content';
$lang[30] = 'Enter the content of this template (required)';
$lang[31] = 'The Template was successfully updated';
$lang[32] = 'Template Browser';
$lang[33] = 'title';
$lang[34] = 'updated';
$lang[35] = 'size';
$lang[36] = 'edit';
$lang[37] = 'delete';
$lang[38] = 'Delete this template?';
$lang[39] = '<p>No Templates have been created yet<br>Press &quot;Save As New Template&quot; when creating a group email to save it as a template</p>';
$lang[40] = 'The template was successfully deleted';
$lang[41] = 'Create a New Group Email';
$lang[42] = 'Group Email Browser';
$lang[43] = 'subject';
$lang[44] = 'sent';
$lang[45] = 'recipients';
$lang[46] = 'Delete this group email?';
$lang[47] = '<p>No Group Emails have been created - press Create a New Email above to create one.</p>';
$lang[48] = 'The group email was successfully deleted';
$lang[49] = 'The template update was successfully saved';
$lang[50] = 'Group: &nbsp;';
$lang[51] = 'Recipients:';
$lang[52] = 'Creator:';
