<?php
/**
 * Jamroom Blog module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'blog';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Create a Blog';
$lang[2]  = 'Create New Blog';
$lang[3]  = 'Blog Title';
$lang[4]  = 'Enter a title for this blog';
$lang[5]  = 'Blog Category';
$lang[6]  = 'Select a category for this blog or enter a new one';
$lang[7]  = 'Blog Text';
$lang[8]  = 'Enter the contents of your Blog post';
$lang[9]  = 'Blog List Image';
$lang[10] = 'Optionally upload a blog image. This image is used in blog lists as the default image for the post.';
$lang[11] = 'select';
$lang[12] = 'An error was encountered creating the blog - please try again.';
$lang[14] = 'Invalid id - please pass in a valid blog id.';
$lang[15] = 'The blog entry was not found in the datastore - please try again.';
$lang[16] = 'update blog';
$lang[17] = 'update';
$lang[19] = 'Posted a new blog';
$lang[20] = 'Category';
$lang[21] = 'Content';
$lang[22] = 'Blog Publish Date';
$lang[23] = 'This is the date that will appear on the blog.  If this date is in the future, this blog post will not be shown until then.';
$lang[24] = 'Blog';
$lang[25] = 'Read more';
$lang[26] = 'Posted in';
$lang[27] = 'comments';
$lang[28] = 'By';
$lang[29] = 'Blogs';
$lang[30] = "Updated a Blog";
$lang[31] = 'Subscribe';
$lang[32] = 'Categories';
$lang[33] = 'Page';
