<?php
/**
 * Jamroom jrBeatSlinger skin
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom Beat Slinger - lang strings
 * @copyright 2003 - 2017 by The Jamroom Network - All Rights Reserved
 */


// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Home';
$lang[2]  = 'create';
$lang[3]  = 'Share';
$lang[4]  = 'By Newest';
$lang[5]  = 'Alphabetically';
$lang[6]  = 'By Most Plays';
$lang[7]  = 'By Most Likes';
$lang[8]  = 'Albums';
$lang[9]  = 'Timeline';
$lang[10] = 'Profile';
$lang[11] = 'Online Status';
$lang[12] = 'About';
$lang[13] = 'Stats';
$lang[14] = 'Influences';
$lang[15] = 'Latest Followers';
$lang[16] = 'Contact';
$lang[17] = 'Update Status';
$lang[18] = 'Followers';
$lang[19] = 'Mentions';
$lang[20] = 'Blog';
$lang[21] = 'Album';
$lang[22] = 'Categories';
$lang[23] = 'Blog';
$lang[24] = 'Follow';
$lang[25] = 'Login';
$lang[26] = 'is now following';
$lang[27] = 'Change Image';
$lang[28] = 'Sign Up';
$lang[29] = 'Dashboard';
$lang[30] = 'Calendar';
$lang[31] = 'Most Popular';
$lang[32] = '30 Day Chart';
$lang[33] = 'Visit Us on Social Media';
$lang[34] = 'Click to see full image';
$lang[35] = 'Cart';
$lang[36] = 'Search';
$lang[37] = 'Play';
$lang[38] = 'Plays';
$lang[39] = 'Genre';
$lang[40] = 'Created';
$lang[41] = 'Category';
$lang[42] = 'Title';
$lang[43] = 'Buy';
$lang[44] = 'Add';
$lang[45] = 'Duration';
$lang[46] = 'Artist';
$lang[47] = 'Description';
$lang[48] = 'Del';
$lang[49] = 'Log in';
$lang[50] = 'Sign up';
$lang[51] = 'system tools';
$lang[52] = 'activity logs';
$lang[53] = 'reset caches';
$lang[54] = 'integrity check';
$lang[55] = 'system updates';
$lang[56] = 'system check';
$lang[57] = 'users';
$lang[58] = 'quota browser';
$lang[59] = 'profile browser';
$lang[60] = 'user accounts';
$lang[61] = 'users online';
$lang[62] = 'skin settings';
$lang[63] = 'skin notes';;
$lang[64] = 'user menu editor';
$lang[65] = 'skin images';
$lang[66] = 'skin style';
$lang[67] = 'skin templates';
$lang[68] = 'dashboard';
$lang[69] = 'ACP';
$lang[70] = 'Status';
$lang[71] = 'Read More';
$lang[72] = 'See More';
$lang[73] = 'Watch Now';
$lang[74] = 'Listen Now';
$lang[75] = 'posted';
$lang[76] = 'joined';
$lang[77] = 'Tap Again';
$lang[78] = "What's on your mind?...";
$lang[79] = 'Post';
$lang[80] = 'Reply';
$lang[81] = 'No Items Found';
$lang[82] = "Wait 'til they get a load of me";
$lang[83] = "We have the world's best music from the world's coolest community";
$lang[84] = "More Top Picks";
$lang[85] = "Join us and get hundreds of downloads from top rated artists.";
$lang[86] = "See More Downloads";
$lang[87] = "Retain up to 100% of your earnings and get loads of sales.";
$lang[88] = "Learn More";
$lang[89] = "PRO offer:";
$lang[90] = "Unlimited storage space";
$lang[91] = "100% of sales receipts";
$lang[92] = "Social network sharing";
$lang[93] = "Upload videos";
$lang[94] = "Profile banners";
$lang[95] = "We are about sharing, networking and most of all listening.";
$lang[96] = "Responsive Design";
$lang[97] = "5 Video Backgrounds";
$lang[98] = "Social Media Timeline";
$lang[99] = "Ready to go with a few clicks";
$lang[100] = "minimize";
$lang[101] = "maximize";
$lang[102] = "Playlist";
$lang[103] = "Comments";
$lang[104] = "Start Listening";
$lang[105] = "Featured Writers";
$lang[106] = "Create a post";
$lang[107] = "follow this author";
$lang[108] = "with facebook and other networks.";
$lang[109] = "comments";
$lang[110] = "likes";
$lang[111] = "You may also like";
$lang[112] = "Start Creating";
$lang[113] = "Images";
$lang[114] = "Post Images";
$lang[115] = "Basic Info";
$lang[116] = "Lyrics";
$lang[117] = "Shared";
$lang[118] = "Load More";
$lang[119] = "Back To Top";
$lang[120] = "Feedback";
$lang[121] = "posts";
$lang[122] = "Write a comment ...";
$lang[123] = "More";
$lang[124] = "Update Cover Image";
$lang[125] = "currently";
$lang[126] = "Followers";
$lang[127] = "Mentions";
$lang[128] = "Feedback";
$lang[129] = "commented on";
$lang[130] = "joined";
$lang[131] = "Biography";
$lang[132] = "Read Full Biography";
$lang[133] = "rated";
$lang[134] = "with a";
$lang[135] = "Auto Play";
$lang[136] = "Auto Mute";
$lang[137] = "More";
$lang[138] = "read more";
$lang[139] = "listen now";
$lang[140] = "watch";
$lang[141] = "view";
$lang[142] = "views";
$lang[143] = "Return to Feed";
$lang[145] = "Following";
$lang[144] = "Updates";
$lang[146] = "Trending";
$lang[147] = "Welcome back";
$lang[148] = "You must be logged in to create";
$lang[149] = "Popular Posts";
$lang[150] = "Recommended";
$lang[151] = "Create an Event";
$lang[152] = "Update Your Status";
$lang[153] = "More";
$lang[155] = "Tracks";
$lang[156] = "No items found";
$lang[157] = "Edit Configuration";
$lang[158] = "Audio Text";
$lang[159] = "Enter a description of this audio file";
$lang[160] = "Audio Lyrics";
$lang[161] = "Enter the lyrics for this audio song";
$lang[162] = "Video Text";
$lang[163] = "Enter a description for this video";
$lang[164] = "Video Category";
$lang[165] = "Enter a category for this video";
$lang[166] = "Cover Image";
$lang[167] = "Enter the home location for this profile";
$lang[168] = "Website";
$lang[169] = "must include http://";
$lang[170] = "Enter the home website for this profile";
$lang[171] = "Location";
$lang[172] = "City, State";
$lang[173] = "Enter the home location for this profile";
