<?php
/**
 * Jamroom jrFlashback skin
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 Flashback Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Home';
$lang[2]  = 'create';
$lang[3]  = 'account';
$lang[4]  = 'profile';
$lang[5]  = 'logout';
$lang[6]  = 'login';
$lang[7]  = 'welcome to';
$lang[8]  = 'site';
$lang[9]  = 'News';
$lang[10] = 'Blog';
$lang[11] = 'newest';
$lang[12] = 'profiles';
$lang[13] = 'Songs';
$lang[14] = 'Videos';
$lang[15] = 'YouTube';
$lang[16] = 'ACP';
$lang[17] = 'dashboard';
$lang[18] = 'pages';
$lang[19] = 'Events';
$lang[20] = 'menu';
$lang[21] = 'featured';
$lang[22] = 'all';
$lang[23] = 'see all';
$lang[24] = 'Search';
$lang[25] = 'Change Image';
$lang[26] = 'Community';
$lang[27] = 'Charts';
$lang[28] = 'lists';
$lang[29] = 'Galleries';
$lang[30] = 'Events';
$lang[31] = 'find new music';
$lang[32] = 'Enter an Artist you would like to find music similar to';
$lang[33] = 'top blog\'s';
$lang[34] = 'Archive';
$lang[35] = 'our sponsors';
$lang[36] = 'stats';
$lang[37] = 'Master';
$lang[38] = 'Site';
$lang[39] = 'Admins';
$lang[40] = 'Members';
$lang[41] = 'Visitors';
$lang[42] = 'house';
$lang[43] = 'radio';
$lang[44] = 'channel';
$lang[45] = 'who\'s online';
$lang[46] = 'most';
$lang[47] = 'viewed';
$lang[48] = 'Artists';
$lang[49] = 'played';
$lang[50] = 'views';
$lang[51] = 'plays';
$lang[52] = 'listeners';
$lang[53] = 'weekly';
$lang[54] = 'monthly';
$lang[55] = 'yearly';
$lang[56] = 'Music';
$lang[57] = 'Video';
$lang[58] = 'Top';
$lang[59] = 'by plays';
$lang[60] = 'by rating';
$lang[61] = '1 week';
$lang[62] = '1 month';
$lang[63] = '1 year';
$lang[64] = 'album';
$lang[65] = 'position';
$lang[66] = 'alphabetically';
$lang[67] = 'Articles';
$lang[68] = 'upcoming';
$lang[69] = 'launch';
$lang[70] = 'Total';
$lang[71] = 'SoundCloud';
$lang[72] = 'Vimeo';
$lang[73] = 'YouTube';
$lang[74] = 'Skin Settings';
$lang[75] = 'System Tools';
$lang[76] = 'Albums';
$lang[77] = 'Comments';
$lang[78] = 'Latest';
$lang[79] = 'Terms Of Service';
$lang[80] = 'Privacy Policy';
$lang[81] = 'Contact Us';
$lang[82] = 'subject';
$lang[83] = 'message';
$lang[84] = 'Please enter the message you would like to send';
$lang[85] = 'Modify Settings';
$lang[86] = ' and we will get back to you ASAP.';
$lang[87] = 'Cancel';
$lang[88] = 'Send Message';
$lang[89] = 'You have not added your contact info in the skin settings! Modify the contact settings by clicking the gear button to the right.';
$lang[90] = 'Sorry! We have not added our info for this section yet.';
$lang[91] = 'Activity Logs';
$lang[92] = 'Reset Cache';
$lang[93] = 'Integrity Check';
$lang[94] = 'Banned Items';
$lang[95] = 'Skin Menu Editor';
$lang[96] = 'Create Sitemap';
$lang[97] = 'System Check';
$lang[98] = 'moved';
$lang[99] = 'About';
$lang[100] = 'Followers';
$lang[101] = 'categories';
$lang[102] = 'Subscribe';
$lang[103] = 'Developer Tools';
$lang[104] = 'Reset Image Cache';
$lang[105] = 'Reset';
$lang[106] = 'Blogs';
$lang[107] = 'Files';
$lang[108] = 'Download';
$lang[109] = 'Recently Rated';
$lang[110] = 'Influences';
$lang[111] = 'Quota Browser';
$lang[112] = 'User Accounts';
$lang[113] = 'activity feed';
$lang[114] = 'Profile Browser';
$lang[115] = 'Who\'s Online';
$lang[116] = 'Users';
$lang[117] = 'Commented on the';
$lang[118] = 'System Updates';
$lang[119] = 'Debug Logs';
$lang[120] = 'PHP Error Logs';
$lang[121] = 'Skin Notes';
$lang[122] = 'Skin Style';
$lang[123] = 'Skin Images';
$lang[124] = 'Skin Templates';
$lang[125] = 'Skin Language';
$lang[126] = 'joined';
$lang[127] = 'artist';
$lang[128] = 'Sorry, No Users Online!';
$lang[129] = 'You Can Help Make This Site';
$lang[130] = 'Active By Logging In!';
$lang[131] = 'OR';
$lang[132] = 'Cart';
