<?php
/**
 * Jamroom Files module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'file';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Create File for Download';
$lang[2]  = 'Create';
$lang[3]  = 'File Title';
$lang[4]  = 'The file title that will be shown for the download link';
$lang[5]  = 'File';
$lang[6]  = 'Select the file to upload';
$lang[7]  = 'select file';
$lang[8]  = 'Update File for Download';
$lang[9]  = 'Update';
$lang[10] = 'Download';
$lang[11] = 'files';
$lang[12] = 'title';
$lang[13] = 'file name';
$lang[14] = 'size';
$lang[15] = 'insert';
$lang[16] = 'profile';
$lang[17] = 'no files were found';
$lang[18] = 'Uploaded a new File';
$lang[19] = 'File List Image';
$lang[20] = 'Optionally upload a file image. This image is used as in file lists as the default image for the file.';
$lang[21] = 'select image';
$lang[22] = 'Files';
$lang[23] = "Updated a File";
