<?php
/**
 * Jamroom Event Calendar module
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'events';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]   = 'Create Event';
$lang[2]   = 'Event Title';
$lang[3]   = 'Enter a title for this event';
$lang[4]   = 'Event Description';
$lang[5]   = 'Enter your event description';
$lang[6]   = 'Event Location';
$lang[7]   = 'Enter the location or venue for this event (required)';
$lang[8]   = 'Event Image';
$lang[9]   = 'Upload an event image';
$lang[10]  = 'select image';
$lang[11]  = 'Event Date';
$lang[12]  = 'Select the event date and start time';
$lang[13]  = 'Featuring';
$lang[16]  = 'Recurring Event';
$lang[17]  = 'If this is a recurring event, select the rule that applies, then select the end date. Multiple events with dates based on the selected rule will be created (up to a maximum set by this site).';
$lang[18]  = 'Recurring End Date';
$lang[19]  = 'Selected end date is before the start date';
$lang[20]  = 'Unable to create the event in the database - please try again.';
$lang[22]  = 'event';
$lang[23]  = 'events';
$lang[25]  = 'Invalid _item_id - please try again';
$lang[26]  = 'Cannot retrieve Event data - please try again';
$lang[27]  = 'Update Event';
$lang[28]  = 'Adding this event will exceed the number of events allowed in your plan';
$lang[29]  = 'Adding these events will exceed the number of events allowed in your plan';
$lang[30]  = 'The event entry was not found in the database - please try again.';
$lang[31]  = 'Events';
$lang[32]  = 'Created a new Event';
$lang[33]  = 'Updated an Event';
$lang[34]  = 'Attending?';
$lang[35]  = 'Attending';
$lang[36]  = 'Attended?';
$lang[37]  = 'Attended';
$lang[38]  = 'Attendees';
$lang[39]  = 'Not attending?';
$lang[40]  = 'Did not attend?';
$lang[41]  = 'January';
$lang[42]  = 'February';
$lang[43]  = 'March';
$lang[44]  = 'April';
$lang[45]  = 'May';
$lang[46]  = 'June';
$lang[47]  = 'July';
$lang[48]  = 'August';
$lang[49]  = 'September';
$lang[50]  = 'October';
$lang[51]  = 'November';
$lang[52]  = 'December';
$lang[53]  = 'Event Calendar';
$lang[54]  = 'W';
$lang[55]  = 'Sunday';
$lang[56]  = 'Monday';
$lang[57]  = 'Tuesday';
$lang[58]  = 'Wednesday';
$lang[59]  = 'Thursday';
$lang[60]  = 'Friday';
$lang[61]  = 'Saturday';
$lang[62]  = 'Event End Day';
$lang[63]  = 'If this is a multi day event, enter when it ends';
$lang[64]  = '-';
$lang[65]  = 'Attending Event';
$lang[66]  = 'When an event you are attending is near, how do you want to be notified?';
$lang[67]  = 'Enter the end date for this Recurring event';
$lang[68]  = 'One-off Event';
$lang[69]  = 'Daily';
$lang[70]  = 'Every Sunday';
$lang[71]  = 'Every Monday';
$lang[72]  = 'Every Tuesday';
$lang[73]  = 'Every Wednesday';
$lang[74]  = 'Every Thursday';
$lang[75]  = 'Every Friday';
$lang[76]  = 'Every Saturday';
$lang[77]  = '1st of every month';
$lang[78]  = '2nd of every month';
$lang[79]  = '3rd of every month';
$lang[80]  = '4th of every month';
$lang[81]  = '5th of every month';
$lang[82]  = '6th of every month';
$lang[83]  = '7th of every month';
$lang[84]  = '8th of every month';
$lang[85]  = '9th of every month';
$lang[86]  = '10th of every month';
$lang[87]  = '11th of every month';
$lang[88]  = '12th of every month';
$lang[89]  = '13th of every month';
$lang[90]  = '14th of every month';
$lang[91]  = '15th of every month';
$lang[92]  = '16th of every month';
$lang[93]  = '17th of every month';
$lang[94]  = '18th of every month';
$lang[95]  = '19th of every month';
$lang[96]  = '20th of every month';
$lang[97]  = '21st of every month';
$lang[98]  = '22nd of every month';
$lang[99]  = '23rd of every month';
$lang[100] = '24th of every month';
$lang[101] = '25th of every month';
$lang[102] = '26th of every month';
$lang[103] = '27th of every month';
$lang[104] = '28th of every month';
$lang[105] = '29th of every month';
$lang[106] = '30th of every month';
$lang[107] = '31st of every month';
$lang[108] = 'First Sunday of every month';
$lang[109] = 'First Monday of every month';
$lang[110] = 'First Tuesday of every month';
$lang[111] = 'First Wednesday of every month';
$lang[112] = 'First Thursday of every month';
$lang[113] = 'First Friday of every month';
$lang[114] = 'First Saturday of every month';
$lang[115] = 'Second Sunday of every month';
$lang[116] = 'Second Monday of every month';
$lang[117] = 'Second Tuesday of every month';
$lang[118] = 'Second Wednesday of every month';
$lang[119] = 'Second Thursday of every month';
$lang[120] = 'Second Friday of every month';
$lang[121] = 'Second Saturday of every month';
$lang[122] = 'Third Sunday of every month';
$lang[123] = 'Third Monday of every month';
$lang[124] = 'Third Tuesday of every month';
$lang[125] = 'Third Wednesday of every month';
$lang[126] = 'Third Thursday of every month';
$lang[127] = 'Third Friday of every month';
$lang[128] = 'Third Saturday of every month';
$lang[129] = 'Fourth Sunday of every month';
$lang[130] = 'Fourth Monday of every month';
$lang[131] = 'Fourth Tuesday of every month';
$lang[132] = 'Fourth Wednesday of every month';
$lang[133] = 'Fourth Thursday of every month';
$lang[134] = 'Fourth Friday of every month';
$lang[135] = 'Fourth Saturday of every month';
$lang[136] = 'Last Sunday of every month';
$lang[137] = 'Last Monday of every month';
$lang[138] = 'Last Tuesday of every month';
$lang[139] = 'Last Wednesday of every month';
$lang[140] = 'Last Thursday of every month';
$lang[141] = 'Last Friday of every month';
$lang[142] = 'Last Saturday of every month';
$lang[143] = 'Is attending an Event';
$lang[144] = 'Events you are attending';
$lang[145] = 'No events you are attending found';
$lang[146] = 'You are not attending any events';
$lang[147] = 'Events attending';
$lang[148] = 'My Event Title';
$lang[149] = '1234 Elm Street';
$lang[150] = 'Enter event description here';


