<?php
/**
 * Jamroom Simple Chat module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 * @author Brian Johnson <brian [at] jamroom [dot] net>
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'make chat pane narrower';
$lang[2]  = 'make chat pane wider';
$lang[3]  = 'start a new chat or join an existing chat';
$lang[4]  = 'type message and press enter';
$lang[5]  = 'chat settings';
$lang[6]  = 'save changes';
$lang[7]  = 'notifications';
$lang[8]  = 'Do you want to receive a new web notification when a user posts to a chat room?';
$lang[9]  = 'users in this chat';
$lang[10] = 'Are you sure you want to BLOCK THIS USER from this public chat?';
$lang[11] = 'Are you sure you want to leave this chat? You will not be able to rejoin this chat until the room admin adds you again.';
$lang[12] = 'Are you sure you want to REMOVE THIS USER from this chat?';
$lang[13] = 'add user to chat';
$lang[14] = 'search';
$lang[15] = 'search for a user';
$lang[16] = 'chat room';
$lang[17] = 'new';
$lang[18] = 'go';
$lang[19] = 'Delete this PUBLIC chat room?';
$lang[20] = 'Delete this PRIVATE chat room?';
$lang[21] = 'public';
$lang[22] = 'no chat rooms have been created';
$lang[23] = 'create new room';
$lang[24] = 'private';
$lang[25] = 'private chat';
$lang[26] = 'start a chat with a user';
$lang[27] = 'start chat';
$lang[28] = 'has been added to this chat';
$lang[29] = 'you can only chat with followers';
$lang[30] = 'has left this chat';
$lang[31] = 'has been removed from this chat';
$lang[32] = 'has shared an image';
$lang[33] = 'has shared a file';
$lang[34] = 'is paging';
$lang[35] = 'transcript';
$lang[36] = 'beginning of chat';
$lang[37] = 'no chat rooms! click the icon to create one';
$lang[38] = 'no room selected';
$lang[39] = 'online status';
$lang[40] = 'select your online status';
$lang[41] = 'automatic';
$lang[42] = 'online';
$lang[43] = 'offline';
$lang[44] = 'inactive';
$lang[45] = 'Search Messages';
$lang[46] = 'Chat';
$lang[47] = 'You do not have permission to create a private chat';
$lang[48] = 'no chat room selected';
$lang[49] = 'open chat in separate window';
$lang[50] = 'new message sound';
$lang[51] = 'When a new message is received and chat is not focused do you want the new message sound to play?';
