<?php
/**
 * Jamroom Followers module
 *
 * copyright 2018 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!

// Profile Menu Entry Name
$lang['menu'] = 'followers';

// Keys
$lang[1]  = 'follow';
$lang[2]  = 'following';
$lang[3]  = 'Followers Require Approval';
$lang[4]  = 'If &quot;Followers Require Approval&quot; is checked, anyone following your profile will need to be approved by you before becoming a follower of your profile.';
$lang[5]  = 'pending';
$lang[6]  = 'No longer follow this profile?';
$lang[7]  = "Your follow request is currently pending - once the profile owner approves your follow request, you will be notified";
$lang[8]  = "You are currently following this profile";
$lang[9]  = 'new pending follower';
$lang[10] = 'new follower';
$lang[11] = 'follow approved';
$lang[12] = 'You have a new follower awaiting approval';
$lang[13] = 'user';
$lang[14] = 'If you would like to approve this user to be a new follower, click the the following URL (or cut and paste it into your browser)';
$lang[15] = 'If you would like to ignore or delete this request, click this URL instead (or cut and paste into your browser)';
$lang[16] = 'You have a new follower awaiting approval!';
$lang[17] = 'You are now following';
$lang[18] = 'You can now keep up with what';
$lang[19] = 'is doing';
$lang[20] = 'You have a new';
$lang[21] = 'follower!';
$lang[22] = 'is now following';
$lang[23] = 'If you are approving new followers, do you want to be notified when a new follower is waiting to be approved?';
$lang[24] = 'Do you want to be notified when you get a new follower?';
$lang[25] = 'Do you want to be notified if your pending follow request for another profile is approved?';
$lang[26] = 'followers';
$lang[27] = 'user name';
$lang[28] = 'profile name';
$lang[29] = 'follower since';
$lang[30] = 'approve';
$lang[31] = 'delete';
$lang[32] = 'No followers found';
$lang[33] = 'Are you sure you want to delete this follower?';
$lang[34] = 'You have a new %1 follower!';
$lang[35] = '%1 is now following you:';
$lang[36] = 'You are not following any profiles';
$lang[37] = 'Profiles You Follow';
$lang[38] = 'Share Who you Follow';
$lang[39] = 'If this option is checked, when you follow a new profile an entry will be added to your Timeline for others to view';
$lang[40] = 'Followed by:';
$lang[41] = 'Keep Followers Pending until my Approval';
