<?php
/**
 * Jamroom Image Galleries module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom Image Gallery Module - language strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!

// Profile Menu Entry Name
$lang['menu'] = 'gallery';

// Keys
$lang[1]  = 'upload images';
$lang[2]  = 'create gallery';
$lang[3]  = 'gallery title';
$lang[4]  = 'Select a title for this collection of images';
$lang[5]  = 'Select the images you would like to upload to this Gallery. You can select multiple images and all will be uploaded to the new Gallery.';
$lang[6]  = 'You must upload at least one image file to create a new Gallery!';
$lang[7]  = 'Unable to create the gallery images in the database - please try again.';
$lang[8]  = 'The images were uploaded and the new Gallery was successfully created.';
$lang[9]  = 'Invalid Gallery URL - please try again.';
$lang[10] = 'gallery images';
$lang[11] = 'upload images';
$lang[12] = 'Unable to retrieve Gallery Images from database - please try again.';
$lang[13] = 'The Gallery was successfully updated';
$lang[14] = 'Invalid Gallery image id - please try again';
$lang[15] = 'image detail';
$lang[16] = 'save changes';
$lang[17] = 'image caption';
$lang[18] = 'Enter a caption for this image to let the viewer know more about the picture.';
$lang[19] = 'The Gallery Image was successfully updated';
$lang[20] = 'detail';
$lang[21] = 'delete';
$lang[22] = 'Are you sure you want to delete this Gallery Image?';
$lang[23] = 'Created a new Gallery';
$lang[24] = 'Image Galleries';
$lang[25] = 'Gallery';
$lang[26] = 'Size';
$lang[27] = '- select image size -';
$lang[28] = 'Position';
$lang[29] = '- select image position -';
$lang[30] = 'normal';
$lang[31] = 'float left';
$lang[32] = 'float right';
$lang[33] = 'insert image';
$lang[34] = 'image options';
$lang[35] = 'Are you sure you want to delete this entire Gallery?';
$lang[36] = 'select the gallery you would like this image to be included in';
$lang[37] = 'View images in Lightbox';
$lang[38] = 'images';
$lang[39] = 'Updated a Gallery';
$lang[40] = 'select images to upload';
$lang[41] = 'Existing Image';
$lang[42] = 'Replace the existing image by uploading a new image';
$lang[43] = 'Upload New Image';
$lang[44] = 'stretch';
$lang[45] = 'no gallery images were found';
$lang[46] = 'image title';
$lang[47] = 'Enter a title for this image';
$lang[48] = 'View All Images';
$lang[49] = 'Edit Image';
$lang[50] = 'Press &quot;Save Changes&quot; to save your image modifications';
$lang[51] = 'download this image';
$lang[52] = 'Margin';
$lang[53] = 'Toggle Crop';
$lang[54] = 'No image id received, so cant update database';
$lang[55] = 'item not found in datastore';
$lang[56] = 'permission denied';
$lang[57] = 'not a valid title';
$lang[58] = '(no title)';
$lang[59] = 'search images';
$lang[60] = 'select image';
$lang[61] = 'Image Title';
$lang[62] = 'add images to gallery';
