<?php
/**
 * Jamroom Profile Tweaks module
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Customize';
$lang[2]  = 'customize your profile';
$lang[3]  = 'save changes';
$lang[4]  = 'background image ';
$lang[5]  = 'JPG image format only';
$lang[6]  = 'Select a custom JPG background image for your profile';
$lang[7]  = 'select background image - JPG only';
$lang[8]  = 'background style';
$lang[9]  = 'tile image';
$lang[10] = 'If this option is checked, the background image will be presented Tiled - left unchecked the image will be Full Screen.';
$lang[11] = 'profile index';
$lang[12] = 'Select the page of your profile that you would like to be the index page for your profile.';
$lang[13] = 'Your customizations have been successfully saved';
$lang[14] = 'page';
$lang[15] = 'Profile Index (default)';
$lang[16] = 'logo image';
$lang[17] = 'Select a custom Logo that will be used in place of the system logo when viewing your profile.';
$lang[18] = 'select logo image';
$lang[19] = 'profile skin';
$lang[20] = 'If you would like to use a different Skin for your profile, select the skin you would like to use';
$lang[21] = '(default)';
