<?php
/**
 * Jamroom Group Pages module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!

$lang['menu'] = 'Group Page';

$lang[1] = 'Group Pages';
$lang[2] = 'Create New Group Page';
$lang[3] = 'Page Title';
$lang[4] = 'Enter a title for this page';
$lang[5] = 'An error was encountered creating the page - please try again.';
$lang[6] = 'Invalid id - please pass in a valid page id.';
$lang[7] = 'The page entry was not found in the datastore - please try again.';
$lang[8] = 'update page';
$lang[9] = 'update';
$lang[10] = 'Group Page';
$lang[11] = 'Posted a new Group Page';
$lang[12] = 'Updated a Group Page';
$lang[15] = 'body';
$lang[16] = 'The body of this page';
$lang[17] = 'Associated Group';
$lang[18] = 'Optionally select a Group for this npage to be associated with';
$lang[19] = 'View full screen';
