<?php
/**
 * Jamroom jrNovaLight skin
 *
 * copyright 2016 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 Nova Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DuRING INSTALLATION.
// ANY CHANGES TO LANGuAGE STRINGS SHOuLD BE DONE IN THE CONTROL PANEL!
$lang[1] = 'Inicio';
$lang[2] = 'crear';
$lang[3] = 'cuenta';
$lang[4] = 'perfil';
$lang[5] = 'salir';
$lang[6] = 'ingresar';
$lang[7] = 'bienvenido a';
$lang[8] = 'sitio';
$lang[9] = 'Noticias';
$lang[10] = 'Blog';
$lang[11] = 'lo más reciente';
$lang[12] = 'Artistas';
$lang[13] = 'Canciones';
$lang[14] = 'Videos';
$lang[15] = 'YouTube';
$lang[16] = 'administrador';
$lang[17] = 'Tablero De Mandos';
$lang[18] = 'páginas';
$lang[19] = 'Eventos';
$lang[20] = 'menú';
$lang[21] = 'destacado';
$lang[22] = 'todo';
$lang[23] = 'ver todo';
$lang[24] = 'buscar';
$lang[25] = 'Cambiar Imágen';
$lang[26] = 'APC';
$lang[27] = 'Gráficos';
$lang[28] = 'Canción';
$lang[29] = 'Video';
$lang[30] = 'Conciertos';
$lang[31] = 'top';
$lang[32] = 'Semanal';
$lang[33] = 'Mensual';
$lang[34] = 'Anual';
$lang[35] = 'Comunidad';
$lang[36] = 'últimos artículos';
$lang[37] = 'Afiliados';
$lang[38] = 'usuarios';
$lang[39] = 'en línea';
$lang[40] = 'carrito';
$lang[41] = 'más';
$lang[42] = 'estadísticas';
$lang[43] = 'radio';
$lang[44] = 'TV';
$lang[45] = 'Configuraciones';
$lang[46] = 'movido';
$lang[47] = 'posición';
$lang[48] = 'por nombre';
$lang[49] = 'reproducciones';
$lang[50] = 'por reproducciones';
$lang[51] = 'lo que viene';
$lang[52] = 'Archivos';
$lang[53] = 'Artículo';
$lang[54] = 'por clasificación';
$lang[55] = 'perfiles';
$lang[56] = 'maestro';
$lang[57] = 'administradores';
$lang[58] = 'Miembros';
$lang[59] = 'visitantes';
$lang[60] = 'total';
$lang[61] = 'SoundCloud';
$lang[62] = 'YouTube';
$lang[63] = 'Vimeo';
$lang[64] = 'Skin';
$lang[65] = 'Herramientas De Sistema';
$lang[66] = 'Términos Del Servicio';
$lang[67] = 'Política De Privacidad';
$lang[68] = 'Contactanos';
$lang[69] = 'tema';
$lang[70] = 'mensaje';
$lang[71] = 'Puedes contactarnos mediante la dirección, dirección de correo electrónico o número de teléfono que aparece debajo.';
$lang[72] = 'Modificar Configuraciones';
$lang[73] = 'Por favor, ingresa el mensaje a enviar';
$lang[74] = ' y te contestaremos a la brevedad.';
$lang[75] = 'Enviar Mensaje';
$lang[76] = 'No has agregado tu información de contacto en la configuración del skin! Modifica la configuración de contacto haciendo clic en el botón de configuraciones a la derecha.';
$lang[77] = 'Disculpa! No hemos agregado la información de esta sección aún.';
$lang[78] = 'Registro De Actividades';
$lang[79] = 'Reiniciar Caché';
$lang[80] = 'Comprobación De Identidad';
$lang[81] = 'Objetos prohibidos';
$lang[82] = 'Editor de skin del menú';
$lang[83] = 'Crear Mapa Del Sitio';
$lang[84] = 'Comprobación Del Sistema';
$lang[85] = 'Cancelar';
$lang[86] = 'Sobre';
$lang[87] = 'Seguidores';
$lang[88] = 'Vistas';
$lang[89] = 'Suscribirse';
$lang[90] = 'categorías';
$lang[91] = 'Herramientas De Desarrolador';
$lang[92] = 'Reiniciar Caché De Imágenes';
$lang[93] = 'Blogs';
$lang[94] = 'Influencias';
$lang[95] = 'Clasificados Recientemente';
$lang[96] = 'Buscador De Quotas';
$lang[97] = 'Cuentas De Usuario';
$lang[98] = 'canal de actividad';
$lang[99] = 'Buscador De Perfiles';
$lang[100] = 'Quién Esta En Línea';
$lang[101] = 'Usuarios';
$lang[102] = 'Configuraciones De Skin';
$lang[103] = 'Artículos';
$lang[104] = 'por lugar';
$lang[105] = 'Creado';
$lang[106] = 'actualizaciones del sistema';
$lang[107] = 'registros de depuración';
$lang[108] = 'Registros PHP error';
$lang[109] = 'piel Notas';
$lang[110] = 'estilo de la piel';
$lang[111] = 'piel Imágenes';
$lang[112] = 'Plantillas piel';
$lang[113] = 'Skin Idioma';
$lang[114] = 'Comentarios';
$lang[115] = 'Lo sentimos, pero no los Usuarios en línea!';
$lang[116] = 'Usted puede ayudar a hacer de este sitio';
$lang[117] = ' Al iniciar la sesión activa!';
$lang[118] = 'O';
