<?php
/**
 * Jamroom FoxyCart Bundles module
 *
 * copyright 2003 - 2016
 * by The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'bundles';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Item Bundles';
$lang[2]  = 'title';
$lang[3]  = 'price';
$lang[4]  = 'sales';
$lang[5]  = 'delete';
$lang[6]  = 'There are no item bundles to show - create a new one using the form below.';
$lang[7]  = 'create new bundle';
$lang[8]  = 'Enter a descriptive title for this new bundle, or select an existing Album that you would like to create a bundle for.';
$lang[9]  = 'Enter a price for this bundle - this will be the price to purchase all items included in this bundle.';
$lang[10] = 'image';
$lang[11] = 'You can upload a special image for this bundle';
$lang[12] = 'An error was encountered creating the bundle - please try again';
$lang[13] = 'The new bundle was successfully created - you can now add items to the new bundle.';
$lang[14] = 'The Item Bundle was successfully deleted';
$lang[15] = 'Are you sure you want to delete this bundle?';
$lang[16] = 'modify';
$lang[17] = 'save changes';
$lang[18] = 'The bundle was successfully updated';
$lang[19] = 'description';
$lang[20] = 'Enter a detailed description of the items found in this bundle.';
$lang[21] = 'album';
$lang[22] = 'album price';
$lang[23] = 'If you would like to charge a special price for this entire album of items, enter it here.';
$lang[24] = '(for all items)';
$lang[25] = 'add to bundle';
$lang[26] = 'add this item to an existing bundle';
$lang[27] = 'new bundle name';
$lang[28] = 'add';
$lang[29] = 'items';
$lang[30] = 'create';
$lang[31] = 'remove from bundle';
$lang[32] = 'Are you sure you want to remove this item from this bundle?';
$lang[33] = 'count';
$lang[34] = 'price';
$lang[35] = 'insert';
$lang[36] = 'item count';
$lang[37] = 'bundle only';
$lang[38] = 'If this option is checked, this item will only be available to purchase as part of an Item Bundle - it will not show a purchase price for the individual item, even if a price exists.';
$lang[39] = 'Available only as part of this bundle!';
$lang[40] = 'Created a new Bundle';
$lang[41] = 'Updated a Bundle';
$lang[42] = 'Bundles that include this item';
$lang[43] = 'Includes the following items';
$lang[44] = 'Save';
$lang[45] = 'no item bundles were found';
$lang[46] = 'update bundle';
