<?php
/**
 * Jamroom Like It module
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Please remove your LIKE before trying to DISLIKE';
$lang[2]  = 'Please remove your DISLIKE before trying to LIKE';
$lang[3]  = 'Activity Update';
$lang[4]  = 'Like';
$lang[5]  = 'Dislike';
$lang[6]  = 'You Liked This!';
$lang[7]  = 'You Disliked This!';
$lang[8]  = 'Liked by';
$lang[9]  = 'Disliked by';
$lang[10] = 'Items You Like or Dislike';
$lang[11] = 'No items liked or disliked';
$lang[12] = 'Item liked';
$lang[13] = 'If one of your items is liked, would you like to be notified?';
$lang[14] = 'Liked/Disliked';
$lang[15] = 'Liked';
$lang[16] = 'Disliked';
$lang[17] = 'Liked Items';
$lang[18] = 'You do not have the privileges to like an item';
$lang[19] = 'You are not allowed to Like your own items';
$lang[20] = 'You must be logged in to like or dislike an item';
$lang[21] = 'Liked a %1 item created by %2:';
$lang[22] = 'Disliked a %1 item created by %2:';
$lang[23] = 'Liked an %1 item created by %2:';
$lang[24] = 'Disliked an %1 item created by %2:';
