<?php
/**
 * Jamroom SoundCloud module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'soundcloud';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Posted a new SoundCloud track';
$lang[2]  = 'create';
$lang[3]  = 'SoundCloud ID or URL';
$lang[4]  = "Enter the numeric SoundCloud track ID, URL, or when clicking on the track's share button, the track link, the track widget code or the track Wordpress code. If any of the latter is entered, this site will attempt to extract the ID from it. The 'share' button can be found on the SoundCloud player, then the code copied and pasted into this field.";
$lang[5]  = 'Unable to extract ID from URL, or an invalid SoundCloud ID';
$lang[6]  = 'Unable to retrieve data for this track from SoundCloud';
$lang[7]  = 'Unable to create SoundCloud item - please try again';
$lang[8]  = 'SoundCloud track created';
$lang[9]  = 'Invalid _item_id - please try again';
$lang[10] = 'Cannot retrieve SoundCloud data - please try again';
$lang[11] = 'Update SoundCloud Track';
$lang[12] = 'Create SoundCloud Track';
$lang[13] = 'update';
$lang[14] = 'Track Title';
$lang[15] = 'Update the title of this SoundCloud track';
$lang[16] = 'Track Genre';
$lang[17] = 'Update the genre of this SoundCloud track';
$lang[18] = 'Artist Name';
$lang[19] = 'Update the artist name of this SoundCloud track';
$lang[20] = 'Track Description';
$lang[21] = 'Update the description of this SoundCloud track';
$lang[22] = 'Invalid _item_id - please try again';
$lang[23] = 'Unable to retrieve SoundCloud data';
$lang[24] = 'SoundCloud track has been updated';
$lang[25] = 'Title';
$lang[26] = 'Artist';
$lang[27] = 'Genre';
$lang[28] = 'Duration';
$lang[29] = 'Description';
$lang[30] = 'search';
$lang[31] = 'search / import';
$lang[32] = 'SoundCloud Search';
$lang[33] = 'Enter the text you want to search for';
$lang[34] = 'Player';
$lang[35] = 'Information';
$lang[36] = 'Track Created';
$lang[37] = 'Track Genre';
$lang[38] = 'Description';
$lang[39] = 'Import';
$lang[40] = 'Search Area';
$lang[41] = 'No SoundCloud Tracks found';
$lang[42] = 'Prev';
$lang[43] = 'Next';
$lang[44] = 'selected SoundCloud tracks imported';
$lang[45] = 'check all';
$lang[46] = 'A normal search will search on soundclouds starting with the title, but if you want to search for a tag, for a type of music, you can enter that here.';
$lang[47] = 'Results';
$lang[48] = 'How many results you want returned from the search?';
$lang[49] = 'Order';
$lang[50] = 'Do you want the results to be sorted and ordered?';
$lang[51] = 'Tags';
$lang[52] = 'Created';
$lang[53] = 'SoundCloud';
$lang[54] = 'Image';
$lang[55] = 'play';
$lang[56] = 'pause';
$lang[57] = 'Flash Required';
$lang[58] = 'TIP: Use the SoundCloud Search tool to import multiple tracks at a time:';
$lang[59] = 'Updated a SoundCloud Track';
$lang[60] = 'SoundCloud Tracks';
$lang[61] = 'This SoundCloud track already uploaded';
$lang[62] = 'Posted new SoundCloud tracks';
$lang[63] = 'Import';
$lang[64] = 'Inc. Tags';
$lang[65] = 'Create Tags';
$lang[66] = 'The SoundCloud track may have tags associated with it. If so, check this box and they will also be created.';
$lang[67] = 'Search String';
$lang[68] = 'Add SoundCloud';
