<?php
/**
 * Jamroom jrNova skin
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 Nova Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1] = 'domov';
$lang[2] = 'ustvari';
$lang[3] = 'račun';
$lang[4] = 'profil';
$lang[5] = 'odjaviti se';
$lang[6] = 'prijaviti se';
$lang[7] = 'dobrodošli';
$lang[8] = 'stran';
$lang[9] = 'novice';
$lang[10] = 'blog';
$lang[11] = 'najnovejši';
$lang[12] = 'skupina';
$lang[13] = 'skladbe';
$lang[14] = 'videi';
$lang[15] = 'YouTube';
$lang[16] = 'skrbnik';
$lang[17] = 'armaturna plošča';
$lang[18] = 'strani';
$lang[19] = 'dogodki';
$lang[20] = 'meni';
$lang[21] = 'predstavljeni';
$lang[22] = 'vsi';
$lang[23] = 'videti vse';
$lang[24] = 'iskati';
$lang[25] = 'spremeni sliko';
$lang[26] = 'SNP';
$lang[27] = 'grafikon';
$lang[28] = 'pesem';
$lang[29] = 'video';
$lang[30] = 'koncerti';
$lang[31] = 'na vrhu';
$lang[32] = 'tedenski';
$lang[33] = 'mesečni';
$lang[34] = 'letni';
$lang[35] = 'skupnost';
$lang[36] = 'zadnji članki';
$lang[37] = 'partnerji';
$lang[38] = 'uporabniki';
$lang[39] = 'na spletu';
$lang[40] = 'voziček';
$lang[41] = 'več';
$lang[42] = 'statistika';
$lang[43] = 'radio';
$lang[44] = 'televizija';
$lang[45] = 'nastavitve';
$lang[46] = 'premaknjen';
$lang[47] = 'pozicija';
$lang[48] = 'po imenu';
$lang[49] = 'igra';
$lang[50] = 'igrano';
$lang[51] = 'naslednji';
$lang[52] = 'arhiv';
$lang[53] = 'članek';
$lang[54] = 'z oceno';
$lang[55] = 'profili';
$lang[56] = 'gospodar';
$lang[57] = 'skrbniki';
$lang[58] = 'člani';
$lang[59] = 'obiskovalci';
$lang[60] = 'celoten';
$lang[61] = 'SoundCloud';
$lang[62] = 'YouTube';
$lang[63] = 'Vimeo';
$lang[64] = 'koža';
$lang[65] = 'sistemska orodja';
$lang[66] = 'splošni pogoji';
$lang[67] = 'politika zasebnosti';
$lang[68] = 'kontaktirajte nas';
$lang[69] = 'predmet';
$lang[70] = 'sporočilo';
$lang[71] = 'lahko nas kontaktirate z uporabo naslova, internetnega poštnega naslova ali telefonske številke napisane spodaj.';
$lang[72] = 'spreminjanje nastavitev';
$lang[73] = 'prosim vpiši sporočilo, ki ga hočeš poslati';
$lang[74] = ' sporočili vam bomo v najkrajšem možnem času.';
$lang[75] = 'pošlji sporočilo';
$lang[76] = 'Niste dodali svoje podatke v nastavitvah kože! Spremenite nastavitve za stike s klikom na desni prestavni gumb.';
$lang[77] = 'Oprostite! Nismo še dodali naše podatke za ta odsek.';
$lang[78] = 'Dnevnik dejavnosti';
$lang[79] = 'ponastavi predpomnilnik.';
$lang[80] = 'preverjanje celovitosti';
$lang[81] = 'prepovedani predmeti';
$lang[82] = 'urejevalnik menija kože ';
$lang[83] = 'ustvari zemljevid strani';
$lang[84] = 'preizkus sistema';
$lang[85] = 'prekliči';
$lang[86] = 'o';
$lang[87] = 'sledilci';
$lang[88] = 'pogledi';
$lang[89] = 'podpisati';
$lang[90] = 'kategorije';
$lang[91] = 'razvijalčeva orodja';
$lang[92] = 'ponastavitev slike predpomnilnika';
$lang[93] = 'blogi';
$lang[94] = 'vplivi';
$lang[95] = 'ocenjeno pred kratkim';
$lang[96] = 'brskalnik kvote';
$lang[97] = 'uporabniški računi';
$lang[98] = 'objave';
$lang[99] = 'iskalnik profila';
$lang[100] = 'kdo je prijavljen';
$lang[101] = 'uporabniki';
$lang[102] = 'nastavitve kože';
$lang[103] = 'članki';
$lang[104] = 'glede na lokacijo';
$lang[105] = 'ustvarjen';
$lang[106] = 'sistem posodobitve';
$lang[107] = 'debug Dnevniki';
$lang[108] = 'Dnevniki PHP napakah';
$lang[109] = 'kožne Notes';
$lang[110] = 'Style kože';
$lang[111] = 'kožne Slike';
$lang[112] = 'kožne Predloge';
$lang[113] = 'koža jezik';
$lang[114] = 'Komentarji';
$lang[115] = 'Žal, ni uporabnikov na spletu!';
$lang[116] = 'Si lahko pomaga, da to spletno mesto';
$lang[117] = 'Aktivno se prijavite v!';
$lang[118] = 'ALI';
