<?php
/**
 * Jamroom Timeline module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 * @author Brian Johnson <brian [at] jamroom [dot] net>
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!

// Profile Menu Entry Name
$lang['menu'] = 'Timeline';

// Keys
$lang[1]  = 'Created new Item';
$lang[2]  = 'Posted a new Update';
$lang[3]  = 'Status Update';
$lang[4]  = 'Timeline';
$lang[5]  = 'save update';
$lang[6]  = 'characters left';
$lang[7]  = 'Mentions';
$lang[8]  = 'Search';
$lang[9]  = 'Share this update with your followers?';
$lang[10] = 'Share This';
$lang[11] = 'Activity Stream';
$lang[12] = 'mentioned in activity stream';
$lang[13] = 'share to timeline';
$lang[14] = 'Share this action with your followers in your timeline.';
$lang[15] = 'timeline updates';
$lang[16] = 'If your profile name is mentioned in an Activity Stream do you want to be notified?';
$lang[17] = 'You have just been mentioned by %1!';
$lang[18] = '%1 has mentioned you:';
$lang[19] = 'A list of the most recent %1 actions by %2';
$lang[20] = 'share this: ';
$lang[21] = "shared";
$lang[22] = "comments";
$lang[23] = "link to this";
$lang[24] = "Shared By";
$lang[25] = "follower(s)";
$lang[26] = "shared by you";
$lang[27] = "Timeline Update";
$lang[28] = "Update";
$lang[29] = "Timeline Entry";
$lang[30] = "Update your Timeline post";
$lang[31] = 'timeline feed';
$lang[32] = 'Add a Comment';
$lang[33] = 'Share';
$lang[34] = 'Share This with your Followers';
$lang[35] = 'You have shared this with your Followers';
$lang[36] = 'Who To Follow';
$lang[37] = 'Notifications';
$lang[38] = 'item is shared';
$lang[39] = 'If an item of yours is shared do you want to be notified?';
$lang[40] = 'mentioned';
$lang[41] = 'view';
$lang[42] = 'posted';
$lang[43] = 'created an item';
$lang[44] = 'updated an item';
