<?php
/**
 * Jamroom Groups module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'groups';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Groups';
$lang[2]  = 'Create New Group';
$lang[3]  = 'Group Title';
$lang[4]  = 'Enter the title of this group';
$lang[5]  = 'An error was encountered creating this group - please try again.';
$lang[6]  = 'Invalid id - please pass in a valid group id.';
$lang[7]  = 'The group entry was not found in the datastore - please try again.';
$lang[8]  = 'update group';
$lang[9]  = 'update';
$lang[10] = 'Group';
$lang[11] = 'Created a new group';
$lang[12] = 'Updated a group';
$lang[13] = 'Members';
$lang[14] = 'Description';
$lang[15] = 'Enter the description of this group';
$lang[16] = 'Featured';
$lang[17] = 'If checked, this Group will appear in the &quot;featured&quot; section of the Group Listing';
$lang[18] = 'Allow Applicants';
$lang[19] = 'If checked, users are allowed to apply to join this group';
$lang[20] = 'Private Group';
$lang[21] = 'If checked, only members will be allowed to view this group. Detail pages will not show in lists (except to admins and members).  If the direct URL is entered to this Group, then it will be shown so users can apply to become a member.';
$lang[22] = 'group image';
$lang[23] = 'if you would like to associate an image with this group, upload it here';
$lang[24] = 'upload a group image';
$lang[25] = 'My Groups';
$lang[26] = 'Join Group';
$lang[27] = 'Leave Group';
$lang[28] = 'Application Pending';
$lang[29] = 'Are you sure you want to leave this group?';
$lang[30] = 'Are you sure you want to cancel your group application?';
$lang[31] = 'Join this group?';
$lang[32] = 'Group Applications';
$lang[33] = 'Pending group applications';
$lang[34] = 'You have no group applications';
$lang[35] = 'My Group Membership';
$lang[36] = 'You are not a member of any groups';
$lang[37] = 'No groups found';
$lang[38] = 'Comments';
$lang[39] = 'You have no groups created';
$lang[40] = 'My Groups';
$lang[41] = 'Members';
$lang[42] = 'Applied';
$lang[43] = 'Owner';
$lang[44] = 'Joined';
$lang[45] = 'Status';
$lang[46] = 'Approve';
$lang[47] = 'Reject';
$lang[48] = 'Update';
$lang[49] = 'Delete';
$lang[50] = 'Are you sure you want to delete this group?';
$lang[51] = 'New Group comment';
$lang[52] = 'If a group you are a member of is commented on, would you like to be notified?';
$lang[53] = 'new group applicant';
$lang[54] = 'When a user applies to join a private group you have created, how do you want to be notified?';
$lang[55] = 'user leaves group';
$lang[56] = 'When a user leaves a group you have created, do you want to be notified?';
$lang[57] = 'group application accepted';
$lang[58] = 'When your application to a private group is accepted, how do you want to be notified?';
$lang[59] = 'This user is not active in this group - their status is <strong>pending</strong>';
$lang[60] = 'delete this user from this group';
$lang[61] = 'Are you sure you want to delete this user from this group?';
$lang[62] = 'group config for';
$lang[63] = 'active';
$lang[64] = 'If checked, this User will be active in this group';
$lang[65] = 'The User Config has been successfully updated';
$lang[66] = 'Groups You Follow';
$lang[67] = 'Allow Comment Wall';
$lang[68] = 'If checked, the Comment Wall will appear on the Group page allowing users to leave comments';
$lang[69] = 'Comment Wall';
$lang[70] = 'View All';
$lang[71] = 'pending';
$lang[72] = 'pending deletion';
$lang[73] = 'is a Private Group.';
$lang[74] = 'You are already a member of this group';
$lang[75] = 'Your application to this group is currently pending - you will be notified when the status changes';
$lang[76] = 'Apply to Join This Group';
$lang[77] = 'You must be a member to view it - would you like to apply to become a member?';
