<?php
/**
 * Jamroom Page Creator module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'pages';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'create a new page';
$lang[2]  = 'create';
$lang[3]  = 'page title';
$lang[4]  = 'enter a title for this page - this will be used in the URL to view this page.';
$lang[5]  = 'page content';
$lang[6]  = 'enter the content for this page.';
$lang[7]  = 'An error was encountered saving the page - please try again.';
$lang[8]  = 'The new page was successfully created!';
$lang[9]  = 'Invalid page_id - please try again';
$lang[10] = 'update an existing page';
$lang[11] = 'save changes';
$lang[12] = 'The page update was successfully saved.';
$lang[13] = 'page location';
$lang[14] = 'Would you like this page to appear on your profile or on the main site?';
$lang[15] = 'Page is visible on Main Site';
$lang[16] = 'Page is visible on Profile';
$lang[17] = 'view page';
$lang[18] = 'Created a new Page';
$lang[19] = 'Pages';
$lang[20] = 'home';
$lang[21] = 'Updated a Page';
$lang[22] = 'show page header';
$lang[23] = 'If checked, the page title and breadcrumb navigation will be added above the page content.';
$lang[24] = 'allow item features';
$lang[25] = 'If checked, Item Detail features such as comments, tags, etc. will be shown at the bottom of the page.';
