<?php
/**
 * Jamroom Payment Support module
 *
 * copyright 2018 Jamroom Team
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * Jamroom Team
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'payments';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'price';
$lang[2]  = 'If you would like to charge for this item, enter a price.';
$lang[3]  = 'add to cart';
$lang[4]  = 'successfully added to cart';
$lang[5]  = 'continue shopping';
$lang[6]  = 'cart';
$lang[7]  = 'item';
$lang[8]  = 'quantity';
$lang[9]  = 'amount';
$lang[10] = 'shipping';
$lang[11] = 'total';
$lang[12] = 'checkout';
$lang[13] = 'your cart is empty';
$lang[14] = 'cart items';
$lang[15] = 'purchases';
$lang[16] = 'date';
$lang[17] = 'receipt';
$lang[18] = 'no purchases to show in purchase history';
$lang[19] = 'purchaser';
$lang[20] = 'fee';
$lang[21] = 'detail';
$lang[22] = 'transaction detail';
$lang[23] = 'payments';
$lang[24] = 'customers';
$lang[25] = 'products';
$lang[26] = 'clear cart';
$lang[27] = 'remove selected';
$lang[28] = 'Thank you for your purchase!';
$lang[29] = 'view your purchases';
$lang[30] = 'Your transaction is being processed - if you have purchased items for download, you will be notified as soon as they are available for download';
$lang[31] = 'your purchases';
$lang[32] = 'payments email address';
$lang[33] = 'When you sell an item from your profile, what is the email address that you receive payments at?  This email address will be used by the system to send you the proceeds of any sales from your profile.';
$lang[34] = 'refunded';
$lang[35] = 'service charge';
$lang[36] = 'action';
$lang[37] = 'download';
$lang[38] = 'key';
$lang[39] = 'value';
$lang[40] = 'summary';
$lang[41] = 'Sales';
$lang[42] = 'Expense (system fee)';
$lang[43] = 'Income';
$lang[44] = 'graph';
$lang[45] = 'month';
$lang[46] = 'sales';
$lang[47] = 'cleared';
$lang[48] = 'expense';
$lang[49] = 'total';
$lang[50] = 'no sales have been recorded yet';
$lang[51] = 'Invalid Quantity';
$lang[52] = 'The quantity requested could not be filled - the maximum available is %1';
$lang[53] = 'No entries were found that match your search condition';
$lang[54] = 'Payments clear for payout %1 days after being recorded';
$lang[55] = 'All Purchases';
$lang[56] = '-- or --';
