<?php
/**
 * Jamroom Audio module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 * @author Brian Johnson <brian [at] jamroom [dot] net>
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!

// Profile Menu Entry Name
$lang['menu'] = 'audio';

// Keys
$lang[1]  = 'play';
$lang[2]  = 'pause';
$lang[3]  = 'stop';
$lang[4]  = 'mute';
$lang[5]  = 'unmute';
$lang[6]  = 'max volume';
$lang[7]  = 'repeat';
$lang[8]  = 'repeat off';
$lang[9]  = 'create';
$lang[10] = 'title';
$lang[11] = 'Enter a title for the audio file - this will be shown your profile.';
$lang[12] = 'genre';
$lang[13] = 'If you have already entered genres in other audio files, you may select any previous genre, or enter a new genre in text field';
$lang[14] = 'audio file';
$lang[15] = 'select and upload the audio file.';
$lang[16] = 'cover image';
$lang[17] = 'if you would like to associate an image file with this audio file, upload it here. If you do not select a cover image and there is an embedded image in the MP3 file(s), it will be used.';
$lang[18] = 'An error was encountered creating the audio file - please try again.';
$lang[19] = 'The audio file was successfully created!';
$lang[20] = 'Invalid id - please pass in a valid audio id.';
$lang[21] = 'The audio entry was not found in the datastore - please try again.';
$lang[22] = 'create audio file';
$lang[23] = 'update audio file';
$lang[24] = 'update';
$lang[25] = 'The audio file was successfully updated!';
$lang[26] = 'length';
$lang[27] = 'bitrate';
$lang[28] = 'sample rate';
$lang[29] = 'upload a new audio file';
$lang[30] = 'upload a new audio image';
$lang[31] = 'album';
$lang[32] = 'If this audio file is part of an album, enter the album name here.';
$lang[33] = 'Posted a new Audio File';
$lang[34] = 'Albums';
$lang[35] = 'create album';
$lang[36] = 'album audio files';
$lang[37] = 'Select all the audio files that belong to this album - they will be saved individually so they can be edited.';
$lang[38] = 'select audio files';
$lang[39] = 'select cover image';
$lang[40] = 'This audio file is currently being processed and will appear here when complete.';
$lang[41] = 'Audio';
$lang[42] = 'genres';
$lang[43] = 'Flash Required';
$lang[44] = 'previous';
$lang[45] = 'next';
$lang[46] = 'shuffle';
$lang[47] = 'shuffle off';
$lang[48] = 'Update Required';
$lang[49] = 'To play the media you will need to either update your browser to a recent version or update your';
$lang[50] = 'Flash plugin';
$lang[51] = 'streams';
$lang[52] = 'audio tracks';
$lang[53] = 'no audio files were found';
$lang[54] = 'purchase';
$lang[55] = 'Updated an Audio File';
$lang[56] = 'delete album';
$lang[57] = 'Are you sure you want to delete this album?';
$lang[58] = 'You forgot to select an Audio File to upload';
$lang[59] = 'Created a new Audio Album';
$lang[60] = 'modify album';
$lang[61] = 'invalid album name - please try again';
$lang[62] = 'unable to find any audio files that are part of this album';
$lang[63] = 'Updated an Audio Album';
$lang[64] = 'Download this album';
$lang[65] = 'download';
$lang[66] = 'Upload Audio';
$lang[67] = 'audio title';
$lang[68] = 'Created a new Audio File';
$lang[69] = 'Album Not Found';
