<?php
/**
 * Jamroom jrMediaPro skin
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 MediaPro Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Home';
$lang[2]  = 'create';
$lang[3]  = 'account';
$lang[4]  = 'profile';
$lang[5]  = 'logout';
$lang[6]  = 'login';
$lang[7]  = 'Welcome Guest';
$lang[8]  = 'site';
$lang[9]  = 'News';
$lang[10] = 'Blog';
$lang[11] = 'newest';
$lang[12] = 'Profiles';
$lang[13] = 'Songs';
$lang[14] = 'Videos';
$lang[15] = 'YouTube';
$lang[16] = 'ACP';
$lang[17] = 'dashboard';
$lang[18] = 'pages';
$lang[19] = 'Events';
$lang[20] = 'menu';
$lang[21] = 'featured';
$lang[22] = 'all';
$lang[23] = 'see all';
$lang[24] = 'Search';
$lang[25] = 'Change Image';
$lang[26] = 'Community';
$lang[27] = 'Charts';
$lang[28] = 'lists';
$lang[29] = 'Galleries';
$lang[30] = 'Gigs/Events';
$lang[31] = 'find new music';
$lang[32] = 'Can\'t find what you\'re looking for? Enter an Artist you would like to find music similar to';
$lang[33] = 'Gop Blog\'s';
$lang[34] = 'Archive';
$lang[35] = 'Advertisement';
$lang[36] = 'stats';
$lang[37] = 'Master';
$lang[38] = 'Site';
$lang[39] = 'Admins';
$lang[40] = 'Members';
$lang[41] = 'Visitors';
$lang[42] = 'house';
$lang[43] = 'radio';
$lang[44] = 'channel';
$lang[45] = 'who\'s online';
$lang[46] = 'most';
$lang[47] = 'viewed';
$lang[48] = 'Artists';
$lang[49] = 'played';
$lang[50] = 'views';
$lang[51] = 'plays';
$lang[52] = 'listeners';
$lang[53] = 'Weekly';
$lang[54] = 'Monthly';
$lang[55] = 'Yearly';
$lang[56] = 'Music';
$lang[57] = 'Video';
$lang[58] = 'top';
$lang[59] = 'by plays';
$lang[60] = 'by rating';
$lang[61] = '1 week';
$lang[62] = '1 month';
$lang[63] = '1 year';
$lang[64] = 'Album';
$lang[65] = 'position';
$lang[66] = 'alphabetically';
$lang[67] = 'Articles';
$lang[68] = 'upcoming';
$lang[69] = 'Launch';
$lang[70] = 'Total';
$lang[71] = 'SoundCloud';
$lang[72] = 'Vimeo';
$lang[73] = 'YouTube';
$lang[74] = 'Skin Settings';
$lang[75] = 'System Tools';
$lang[76] = 'Albums';
$lang[77] = 'Comments';
$lang[78] = 'Latest';
$lang[79] = 'Terms Of Service';
$lang[80] = 'Privacy Policy';
$lang[81] = 'Contact Us';
$lang[82] = 'subject';
$lang[83] = 'message';
$lang[84] = 'Please enter the message you would like to send';
$lang[85] = 'Modify Settings';
$lang[86] = ' and we will get back to you ASAP.';
$lang[87] = 'Cancel';
$lang[88] = 'Send Message';
$lang[89] = 'You have not added your contact info in the skin settings! Modify the contact settings by clicking the gear button to the right.';
$lang[90] = 'Sorry! We have not added our info for this section yet.';
$lang[91] = 'Activity Logs';
$lang[92] = 'Reset Cache';
$lang[93] = 'Integrity Check';
$lang[94] = 'Banned Items';
$lang[95] = 'Skin Menu Editor';
$lang[96] = 'Create Sitemap';
$lang[97] = 'System Check';
$lang[98] = 'moved';
$lang[99] = 'copyright';
$lang[100] = 'all rights reserved';
$lang[101] = 'Jamroom';
$lang[102] = 'Welcome';
$lang[103] = 'In Box';
$lang[104] = 'Your Home';
$lang[105] = 'Total items in cart';
$lang[106] = 'View';
$lang[107] = 'your cart';
$lang[108] = 'Previous';
$lang[109] = 'Next';
$lang[110] = 'Artist';
$lang[111] = 'Song';
$lang[112] = 'By';
$lang[113] = 'online';
$lang[114] = 'Scheduled';
$lang[115] = 'Exclusive';
$lang[116] = 'Site News';
$lang[117] = 'Site Blog';
$lang[118] = 'About Us';
$lang[119] = 'Today\'s';
$lang[120] = 'Title';
$lang[121] = 'Name';
$lang[122] = 'Joined';
$lang[123] = 'Our Favorite Artist';
$lang[124] = 'Search Results';
$lang[125] = 'Latest Blogs And News';
$lang[126] = 'Reviews And Articles';
$lang[127] = 'Events Calendar';
$lang[128] = 'And';
$lang[129] = 'Tag';
$lang[130] = 'Re';
$lang[131] = 'Followers';
$lang[132] = 'categories';
$lang[133] = 'Subscribe';
$lang[134] = 'Feeds';
$lang[135] = 'Site Blogs';
$lang[136] = 'Our Favorite Song';
$lang[137] = 'Share';
$lang[138] = 'Stations';
$lang[139] = 'Channels';
$lang[140] = 'Blogs';
$lang[141] = 'Reset';
$lang[142] = 'Member';
$lang[143] = 'Influences';
$lang[144] = 'Developer Tools';
$lang[145] = 'Reset Image Cache';
$lang[146] = 'Station Center';
$lang[147] = 'Rating';
$lang[148] = 'Play';
$lang[149] = 'Owner';
$lang[150] = 'Station';
$lang[151] = 'Channel Center';
$lang[152] = 'Channel';
$lang[153] = 'Created';
$lang[154] = 'SoundCloud';
$lang[155] = 'Files';
$lang[156] = 'Download';
$lang[157] = 'Recently Rated';
$lang[158] = 'Quota Browser';
$lang[159] = 'User Accounts';
$lang[160] = 'activity feed';
$lang[161] = 'Profile Browser';
$lang[162] = 'Who\'s Online';
$lang[163] = 'Users';
$lang[164] = 'Reviews';
$lang[165] = 'Powered by';
$lang[166] = 'Bio';
$lang[167] = 'New';
$lang[168] = 'Listeners';
$lang[169] = 'Mix';
$lang[170] = 'length';
$lang[171] = 'singles';
$lang[172] = 'Sounds';
$lang[173] = 'Like';
$lang[174] = 'Hot';
$lang[175] = 'DJ\'s';
$lang[176] = 'Rappers';
$lang[177] = 'Dancers';
$lang[178] = 'Models';
$lang[179] = 'Producers';
$lang[180] = 'Labels';
$lang[181] = 'Top 10';
$lang[182] = 'Genres';
$lang[183] = 'Select A Genre';
$lang[184] = 'Select A Category';
$lang[185] = 'By Album';
$lang[186] = 'Debug Logs';
$lang[187] = 'PHP Error Logs';
$lang[188] = 'User';
$lang[189] = 'System Updates';
$lang[190] = 'Skin Styles';
$lang[191] = 'Skin Images';
$lang[192] = 'Skin Templates';
$lang[193] = 'Skin Language';
$lang[194] = 'Skin Notes';
$lang[195] = 'Groups';
$lang[196] = 'Discussions';
$lang[197] = 'Category';
$lang[198] = 'Location';
$lang[199] = 'About';
$lang[200] = 'Sorry, No Users Online!';
$lang[201] = 'You Can Help Make This Site';
$lang[202] = 'Active By Logging In!';
$lang[203] = 'OR';
