<?php
/**
 * Jamroom jrMediaPro skin
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 MediaPro Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'casa';
$lang[2]  = 'crear';
$lang[3]  = 'cuenta';
$lang[4]  = 'perfil';
$lang[5]  = 'finalizar la sesión';
$lang[6]  = 'iniciar la sesión';
$lang[7]  = 'Bienvenido, invitado';
$lang[8]  = 'sitio';
$lang[9]  = 'noticias';
$lang[10] = 'blog';
$lang[11] = 'el más nuevo';
$lang[12] = 'Perfiles';
$lang[13] = 'canciones';
$lang[14] = 'vídeos';
$lang[15] = 'youtube';
$lang[16] = 'ACP';
$lang[17] = 'salpicadero';
$lang[18] = 'páginas';
$lang[19] = 'eventos';
$lang[20] = 'menú';
$lang[21] = 'destacado';
$lang[22] = 'todos';
$lang[23] = 'ver todas las';
$lang[24] = 'Buscar';
$lang[25] = 'Cambiar imagen';
$lang[26] = 'comunidad';
$lang[27] = 'gráficos';
$lang[28] = 'listas';
$lang[29] = 'galerías';
$lang[30] = 'conciertos / eventos';
$lang[31] = 'encontrar música nueva';
$lang[32] = '¿No encuentras lo que estás buscando? Ingrese un Artista del que desea encontrar música similar a la';
$lang[33] = 'Blog arriba';
$lang[34] = 'archivo';
$lang[35] = 'Anuncio';
$lang[36] = 'estadísticas';
$lang[37] = 'Maestro';
$lang[38] = 'Sitio';
$lang[39] = 'Administradores';
$lang[40] = 'Miembros';
$lang[41] = 'Visitantes';
$lang[42] = 'casa';
$lang[43] = 'radio';
$lang[44] = 'tv canal';
$lang[45] = 'whos línea';
$lang[46] = 'más';
$lang[47] = 'visto';
$lang[48] = 'artistas';
$lang[49] = 'jugado';
$lang[50] = 'visitas';
$lang[51] = 'juega';
$lang[52] = 'oyentes';
$lang[53] = 'Semanal';
$lang[54] = 'Mensual';
$lang[55] = 'Anual';
$lang[56] = 'música';
$lang[57] = 'vídeo';
$lang[58] = 'top';
$lang[59] = 'por obras';
$lang[60] = 'por calificación';
$lang[61] = '1 semana';
$lang[62] = '1 mes';
$lang[63] = '1 año';
$lang[64] = 'álbum';
$lang[65] = 'posición';
$lang[66] = 'alfabéticamente';
$lang[67] = 'artículos';
$lang[68] = 'las próximas';
$lang[69] = 'Lanzar';
$lang[70] = 'Total';
$lang[71] = 'SoundCloud';
$lang[72] = 'Vimeo';
$lang[73] = 'YouTube';
$lang[74] = 'Configuración de la piel';
$lang[75] = 'Herramientas del sistema';
$lang[76] = 'Álbumes';
$lang[77] = 'Comentarios';
$lang[78] = 'último';
$lang[79] = 'Términos de Servicio';
$lang[80] = 'Política de privacidad';
$lang[81] = 'contáctenos';
$lang[82] = 'sujeto';
$lang[83] = 'mensaje';
$lang[84] = 'Por favor, introduzca el mensaje que desea enviar';
$lang[85] = 'Modificación de la configuración';
$lang[86] = ' y nos pondremos en contacto con usted lo antes posible.';
$lang[87] = 'cancelar';
$lang[88] = 'Enviar mensaje';
$lang[89] = 'Usted no ha agregado su información de contacto en los ajustes de la piel! Modificar los ajustes de contactos haciendo clic en el botón de marcha a la derecha.';
$lang[90] = '¡Lo siento! No hemos añadido su información para esta sección todavía.';
$lang[91] = 'Registros de actividad';
$lang[92] = 'Restablecer la caché';
$lang[93] = 'Comprobación integridad';
$lang[94] = 'Artículos Prohibidos';
$lang[95] = 'Skin Editor de menús';
$lang[96] = 'Crear Sitemap';
$lang[97] = 'Comprobación del sistema';
$lang[98] = 'movido';
$lang[99] = 'derechos de autor';
$lang[100] = 'reservados todos los derechos';
$lang[101] = 'Jamroom';
$lang[102] = 'bienvenido';
$lang[103] = 'En Caja';
$lang[104] = 'Su Casa';
$lang[105] = 'Carrito de compra';
$lang[106] = 'ver';
$lang[107] = 'su carrito';
$lang[108] = 'anterior';
$lang[109] = 'próximo';
$lang[110] = 'artista';
$lang[111] = 'canción';
$lang[112] = 'por';
$lang[113] = 'en línea';
$lang[114] = 'Programado';
$lang[115] = 'exclusivo';
$lang[116] = 'Noticias del Sitio';
$lang[117] = 'sitio Blog';
$lang[118] = 'Quiénes somos';
$lang[119] = 'hoy';
$lang[120] = 'título';
$lang[121] = 'nombre';
$lang[122] = 'unido';
$lang[123] = 'Nuestro Artista Favorito';
$lang[124] = 'Resultados de la búsqueda';
$lang[125] = 'Últimos blogs y noticias';
$lang[126] = 'Críticas y artículos';
$lang[127] = 'Calendario de Eventos';
$lang[128] = 'y';
$lang[129] = 'etiqueta';
$lang[130] = 'con respecto a';
$lang[131] = 'Seguidores';
$lang[132] = 'categorías';
$lang[133] = 'suscribir';
$lang[134] = 'Feeds';
$lang[135] = 'Blogs del sitio';
$lang[136] = 'Canción favorita';
$lang[137] = 'participación';
$lang[138] = 'Estaciones';
$lang[139] = 'Canales';
$lang[140] = 'Blogs';
$lang[141] = 'reajustar';
$lang[142] = 'miembro';
$lang[143] = 'Influencias';
$lang[144] = 'instrumentos';
$lang[145] = 'la caché de imagen';
$lang[146] = 'Center Station';
$lang[147] = 'clasificación';
$lang[148] = 'jugar';
$lang[149] = 'propietario';
$lang[150] = 'estación';
$lang[151] = 'Canal Centro';
$lang[152] = 'Canal';
$lang[153] = 'Creado';
$lang[154] = 'SoundCloud';
$lang[155] = 'Archivos';
$lang[156] = 'descargar';
$lang[157] = 'Recientemente clasificados';
$lang[158] = 'Browser Quota';
$lang[159] = 'Cuentas de usuario';
$lang[160] = 'feed de actividad';
$lang[161] = 'Perfil Browser';
$lang[162] = "Quién Está En línea";
$lang[163] = 'Usuarios';
$lang[164] = 'Opiniones';
$lang[165] = 'Desarrollado por';
$lang[166] = 'Bio';
$lang[167] = 'nuevo';
$lang[168] = 'oyentes';
$lang[169] = 'mezclar';
$lang[170] = 'longitud';
$lang[171] = 'individual';
$lang[172] = 'Sonidos';
$lang[173] = 'Como';
$lang[174] = 'Cachondo';
$lang[175] = 'DJ\'s';
$lang[176] = 'Rappers';
$lang[177] = 'Bailarines';
$lang[178] = 'Modelos';
$lang[179] = 'Productores';
$lang[180] = 'Etiquetas';
$lang[181] = 'Top 10';
$lang[182] = 'Géneros';
$lang[183] = 'Seleccione un género';
$lang[184] = 'Seleccione una categoría';
$lang[185] = 'Por álbum';
$lang[186] = 'registros de depuraciÃ³n';
$lang[187] = 'PHP registros de errores';
$lang[188] = 'Usuario';
$lang[189] = 'actualizaciones del sistema';
$lang[190] = 'Estilos piel';
$lang[191] = 'piel Imágenes';
$lang[192] = 'Plantillas piel';
$lang[193] = 'Skin Idioma';
$lang[194] = 'piel Notas';
$lang[195] = 'Grupos';
$lang[196] = 'Discusiones';
$lang[197] = 'categoría';
$lang[198] = 'Ubicación';
$lang[199] = 'Quiénes';
$lang[200] = 'Lo sentimos, pero no los Usuarios en línea!';
$lang[201] = 'Usted puede ayudar a hacer de este sitio';
$lang[202] = ' Al iniciar la sesión activa!';
$lang[203] = 'O';
$lang[204] = 'Carro';
$lang[205] = 'Objetos en tu carro de compras';
