<?php
/**
 * Jamroom jrAudioPro skin
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom Audio Pro - lang strings
 * @copyright 2003 - 2017 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Home';
$lang[2] = 'About';
$lang[3] = 'Log In';
$lang[4] = 'Follow';
$lang[5] = 'Edit';
$lang[6] = 'create profile';
$lang[7] = 'Sign Up';
$lang[8] = 'Click to see full image';
$lang[9] = 'Cart';
$lang[10] = 'Search';
$lang[11] = 'system tools';
$lang[12] = 'activity logs';
$lang[13] = 'reset caches';
$lang[14] = 'integrity check';
$lang[15] = 'system updates';
$lang[16] = 'system check';
$lang[17] = 'users';
$lang[18] = 'quota browser';
$lang[19] = 'profile browser';
$lang[20] = 'user accounts';
$lang[21] = 'users online';
$lang[22] = 'skin settings';
$lang[23] = 'skin notes';;
$lang[24] = 'user menu editor';
$lang[25] = 'skin images';
$lang[26] = 'skin style';
$lang[27] = 'skin templates';
$lang[28] = 'dashboard';
$lang[29] = 'ACP';
$lang[30] = "Title";
$lang[31] = "Artist";
$lang[32] = "Show Playlist";
$lang[33] = "Album";
$lang[34] = "by";
$lang[35] = "Followers";
$lang[36] = "Joined";
$lang[37] = "Biography";
$lang[38] = "Read Full Biography";
$lang[39] = "Auto Play";
$lang[40] = "Auto Mute";
$lang[41] = "Birthday";
$lang[42] = "Tag";
$lang[43] = "Return to Feed";
$lang[44] = "Updates";
$lang[45] = "Following";
$lang[46] = "Trending";
$lang[47] = "Rating";
$lang[48] = "On Sale Now";
$lang[49] = "Featured Artists";
$lang[50] = "Day Charts";
$lang[51] = "Welcome to";
$lang[52] = "Join us today and start creating.";
$lang[53] = "Powerful";
$lang[54] = "Content";
$lang[55] = "Management";
$lang[56] = "We have the world's best music from the world's coolest community";
$lang[57] = "Title";
$lang[58] = "Plays";
$lang[59] = "Birthday";
$lang[60] = "Genre";
$lang[61] = "Days";
$lang[62] = "No items found";
$lang[63] = "This list currently requires items to have a price set.";
$lang[64] = "Edit Configuration.";
$lang[65] = "More";
$lang[66] = "All";
$lang[67] = "Update Cover Image";
$lang[68] = "image caches";
$lang[69] = "Top 200";
$lang[70] = "Video Category";
$lang[71] = 'Enter a category for this video';
$lang[72] = 'Cover Image';
$lang[73] = 'Enter the home location for this profile';
$lang[74] = 'Website';
$lang[75] = 'must include http://';
$lang[76] = 'Location';
$lang[77] = 'City, State';
$lang[78] = 'Enter the home location for this profile';
