<?php
/**
 * Jamroom Comments module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!

// Profile Menu Entry Name
$lang['menu'] = 'comment';

$lang[1]  = 'Your Comment';
$lang[2]  = 'Post Your Comment';
$lang[3]  = 'Commented on';
$lang[4]  = 'item';
$lang[5]  = 'new comment posted';
$lang[6]  = 'New comment on one of your items';
$lang[7]  = 'Your comment was successfully posted';
$lang[8]  = 'An error was encountered saving the comment - please try again';
$lang[9]  = 'There is currently a wait time between posting comments of: ';
$lang[10] = 'You forgot to enter a comment!';
$lang[11] = 'Comments';
$lang[12] = 'Posted a new Comment on';
$lang[13] = 'If a new comment is posted on one of your items, would you like to be notified?';
$lang[14] = 'A new comment has been posted by %1 to one of your items:';
$lang[15] = 'Your comment has been successfully saved, and is pending review by an admin';
$lang[16] = 'You must be logged in to post a comment';
$lang[17] = 'Load More Comments';
$lang[18] = 'Your Reply To:';
$lang[19] = '(deleted)';
$lang[20] = 'Invalid id - please pass in a valid audio id.';
$lang[21] = 'The comment entry was not found in the datastore - please try again.';
$lang[23] = 'update comment text';
$lang[24] = 'update';
$lang[25] = 'The comment text was successfully updated!';
$lang[26] = 'quote this';
$lang[27] = 'new reply to your comment';
$lang[28] = 'If someone responds to one of your comments would you like to be notified?';
$lang[29] = 'You do not have the privileges to view this page';
$lang[30] = 'Posted a new Timeline Comment';
