<?php
/**
 * Jamroom jrSoloArtist skin
 *
 * copyright 2016 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this skin.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom 5 SoloArtist Skin - lang strings
 * @copyright 2003 - 2012 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Home';
$lang[2]  = 'create';
$lang[3]  = 'account';
$lang[4]  = 'profile';
$lang[5]  = 'logout';
$lang[6]  = 'login';
$lang[7]  = 'welcome to';
$lang[8]  = 'site';
$lang[9]  = 'News';
$lang[10] = 'Blog';
$lang[11] = 'latest';
$lang[12] = 'profiles';
$lang[13] = 'Music';
$lang[14] = 'Videos';
$lang[15] = 'YouTube';
$lang[16] = 'ACP';
$lang[17] = 'dashboard';
$lang[18] = '{ages';
$lang[19] = 'Tour dates';
$lang[20] = 'menu';
$lang[21] = 'featured';
$lang[22] = 'all';
$lang[23] = 'see all';
$lang[24] = 'search';
$lang[25] = 'Change Image';
$lang[26] = 'find new music';
$lang[27] = 'search activity stream';
$lang[28] = 'Activity Logs';
$lang[29] = 'Reset Cache';
$lang[30] = 'Reset Image Cache';
$lang[31] = 'Integrity Check';
$lang[32] = 'Banned Items';
$lang[33] = 'Skin Menu Editor';
$lang[34] = 'Create Sitemap';
$lang[35] = 'System Check';
$lang[36] = 'Developer Tools';
$lang[37] = 'System Tools';
$lang[38] = 'Skin Settings';
$lang[39] = 'views';
$lang[40] = 'SoundCloud';
$lang[41] = 'Vimeo';
$lang[42] = 'Blogs';
$lang[43] = 'Followers';
$lang[44] = 'About';
$lang[45] = 'Stats';
$lang[46] = 'View';
$lang[47] = 'Cart';
$lang[48] = 'More';
$lang[49] = 'Music';
$lang[50] = 'Video';
$lang[51] = 'Buy Tickets';
$lang[52] = 'Events';
$lang[53] = 'Comments';
$lang[54] = 'Tour';
$lang[55] = 'Band';
$lang[56] = 'Tracks';
$lang[57] = 'Recently Rated';
$lang[58] = 'Newest';
$lang[59] = 'Activity';
$lang[60] = 'Categories';
$lang[61] = 'Gallery';
$lang[62] = 'Enter an Album name to show a Featured Album player here!';
$lang[63] = 'Album';
$lang[64] = 'Albums';
$lang[65] = 'Files';
$lang[66] = 'Galleries';
$lang[67] = 'Singles';
$lang[68] = 'Change Album';
$lang[69] = 'Influences';
$lang[70] = 'Drag-N-Drop to re-order the list below.';
$lang[71] = 'Our Fans';
$lang[72] = 'Fans';
$lang[73] = 'Streamed';
$lang[74] = 'Downloaded';
$lang[75] = 'Back';
$lang[76] = 'Profile Quota Browser';
$lang[77] = 'User Accounts';
$lang[78] = 'activity feed';
$lang[79] = 'Profile Browser';
$lang[80] = 'Who\'s Online';
$lang[81] = 'Users';
$lang[82] = 'Contact Us';
$lang[83] = 'Terms Of Service';
$lang[84] = 'Privacy Policy';
$lang[85] = 'Please enter the message you would like to send';
$lang[86] = ' and we will get back to you ASAP.';
$lang[87] = 'Cancel';
$lang[88] = 'Send Message';
$lang[89] = 'subject';
$lang[90] = 'message';
$lang[91] = 'System Updates';
$lang[92] = 'Debug Logs';
$lang[93] = 'PHP Error Logs';
$lang[94] = 'Skin Notes';
$lang[95] = 'Skin Styles';
$lang[96] = 'Skin Images';
$lang[97] = 'Skin Templates';
$lang[98] = 'Skin Language';
