<?php
/**
 * Jamroom FoxyCart eCommerce module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'payments';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]   = 'Item Sold';
$lang[2]   = 'add to cart';
$lang[3]   = 'You have not purchased any items yet.';
$lang[4]   = 'download';
$lang[5]   = 'Are you sure you want to delete this item from your purchases?';
$lang[6]   = 'My Items - Cart Purchases';
$lang[7]   = 'price';
$lang[8]   = 'item';
$lang[9]   = 'purchased';
$lang[10]  = 'transaction id';
$lang[11]  = 'If you would like to charge for this item, enter a price.';
$lang[12]  = 'My Sales - Items Sold';
$lang[13]  = 'Earned';
$lang[14]  = 'successfully added to cart';
$lang[15]  = 'You have not sold any items yet';
$lang[16]  = 'your purchases';
$lang[17]  = 'my sales';
$lang[18]  = 'Download all files on this page as a ZIP file:';
$lang[19]  = 'download all';
$lang[20]  = '(per item)';
$lang[21]  = 'new sale';
$lang[22]  = 'purchase details';
$lang[23]  = 'When you make a sale, do you want to receive notification?';
$lang[24]  = 'When you purchase a merchandise item, you will be sent instructions for shipping and seller communication - how do you want to receive these instructions?';
$lang[25]  = 'System Sale';
$lang[26]  = 'When a profile sells something, as a master admin do you want to receive a notification email?';
$lang[27]  = 'Transaction Details - ';
$lang[28]  = 'Enter the transaction id you would like to see details for';
$lang[29]  = 'Transaction Browser';
$lang[30]  = 'Paid Out';
$lang[31]  = 'Sales Tracker';
$lang[32]  = 'Sales Insights';
$lang[33]  = 'Product Performance';
$lang[34]  = 'Subscriptions';
$lang[35]  = '[%1] Your system has sold an item to %2:';
$lang[36]  = 'Notice: Your site has made a new sale to %1 at %2.';
$lang[37]  = 'You can see the payout details here:';
$lang[38]  = 'You can see the transaction details here:';
$lang[39]  = 'Your new %1 password';
$lang[40]  = 'Thank you for your purchase, your account has been created!';
$lang[41]  = 'If your purchase was a download, you can retrieve it here:';
$lang[42]  = 'Your current create password is below';
$lang[43]  = "user login: %1 OR '%2'";
$lang[44]  = 'password: %1';
$lang[45]  = 'Please change your password to one you can remember and change your username if you like';
$lang[46]  = 'We look forward to seeing you online!';
$lang[47]  = '[%1] You have made a new sale to %2.';
$lang[48]  = 'Congratulations!';
$lang[49]  = 'You have just sold an item to %1!';
$lang[50]  = 'You can view the transaction details here:';
$lang[51]  = '[%1] Purchase Details:';
$lang[52]  = 'Thank you for your purchase at %1';
$lang[53]  = 'You can download the downloadables here:';
$lang[54]  = 'If you purchased any postable items, a separate email will come with instructions on how to contact the sellers and progress.';
$lang[55]  = 'buyer user id';
$lang[56]  = 'Product Insights';
$lang[57]  = 'Product Code';
$lang[58]  = 'Now that you have the CSV file, Go pay the profiles. <br><br>After they are paid, reset their balance here to Zero by checking the checkbox then clicking CONTINUE.<br><br>This will reset their account balances to ZERO.';
$lang[59]  = 'Lifetime Earnings';
$lang[60]  = 'code';
$lang[61]  = 'name';
$lang[62]  = 'price';
$lang[63]  = 'qty';
$lang[64]  = 'Earnings';
$lang[65]  = 'Customers';
$lang[66]  = 'seller';
$lang[67]  = 'type';
$lang[68]  = 'buyer';
$lang[69]  = 'name';
$lang[70]  = 'date';
$lang[71]  = 'txn';
$lang[72]  = 'bundle';
$lang[73]  = 'txn_id';
$lang[74]  = 'gross';
$lang[75]  = 'fees';
$lang[76]  = 'net';
$lang[77]  = 'shipping';
$lang[78]  = 'Lifetime Spending';
$lang[79]  = 'Lifetime SpendingProduct Code';
$lang[80]  = 'Product Name';
$lang[81]  = 'Quantity';
$lang[82]  = 'Unique Products';
$lang[83]  = 'Seller';
$lang[84]  = 'Lifetime Sales';
$lang[85]  = 'Current Subscription';
$lang[86]  = 'Id';
$lang[87]  = 'Name';
$lang[88]  = 'Subscription Length';
$lang[89]  = 'Price';
$lang[90]  = 'Available Subscriptions';
$lang[91]  = 'Length';
$lang[92]  = 'Start Subscription';
$lang[93]  = 'Purchase History';
$lang[94]  = 'Transaction ID';
$lang[95]  = 'Start Date';
$lang[96]  = 'Next Transaction';
$lang[97]  = 'End Date';
$lang[98]  = 'Past Due Amt';
$lang[99]  = 'Product Name';
$lang[100] = 'Product Price';
$lang[101] = 'Product Code';
$lang[102] = 'Cancel Subscription';
$lang[103] = 'Change to this Subscription';
$lang[104] = 'Features';
$lang[105] = 'monthly';
$lang[106] = 'yearly';
$lang[107] = 'Your subscription has been updated successfully - your current subscription expires: ';
$lang[108] = 'Expires:';
$lang[109] = 'Starts:';
$lang[110] = 'Your subscription has started successfully - thank you for subscribing!';
$lang[111] = 'Your purchase has been added to your My Items and can be downloaded at any time.  Thank you for your purchase!';
$lang[112] = 'view';
$lang[113] = 'Please log into your account so we can complete the checkout';
$lang[114] = 'Renews:';
$lang[115] = 'Start this new subscription? The amount left on your existing subscription will be credited to the new subscription.';
$lang[116] = 'Are you sure you want to cancel your current subscription and start this new subscription?';
$lang[117] = 'Start this new subscription?';
$lang[118] = 'Trial';
$lang[119] = 'day(s)';
$lang[120] = 'week(s)';
$lang[121] = 'month(s)';
$lang[122] = 'year';
$lang[123] = 'Thank you for your purchase - please log in to view your purchased items.<br>If you do not have an account, one has been created for you - check your email';
$lang[124] = 'Expiring Subscription';
$lang[125] = 'How would you like to be notified if your subscription is about to expire?';
$lang[126] = 'receipt';
