<?php
/**
 * Jamroom Subscriptions module
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'your subscription';
$lang[2]  = 'subscription';
$lang[3]  = 'day';
$lang[4]  = 'week';
$lang[5]  = 'month';
$lang[6]  = 'year';
$lang[7]  = 'days';
$lang[8]  = 'weeks';
$lang[9]  = 'months';
$lang[10] = 'years';
$lang[11] = 'current subscription';
$lang[12] = 'expires';
$lang[13] = 'You do not appear to have an active subscription';
$lang[14] = 'Your subscription has already been canceled';
$lang[15] = 'cancel subscription';
$lang[16] = 'Are you sure you want to cancel your subscription?';
$lang[17] = 'You are currently subscribed to:';
$lang[18] = 'Thank you for becoming a subscriber!';
$lang[19] = 'It could take a few minutes before your new subscription is active.';
$lang[20] = 'Your subscription information has been successfully updated';
$lang[21] = 'Your subscription has been successfully canceled and will expire at the end of the payment period.';
$lang[22] = 'Your subscription is currently active and in the Trial Period - payment begins on: ';
$lang[23] = 'Trial';
$lang[24] = 'View All Subscription Options';
$lang[25] = 'Your subscription expires: ';
$lang[26] = 'update credit card';
$lang[27] = 'subscription canceled';
$lang[28] = 'subscriptions';
$lang[29] = 'subscription payment';
$lang[30] = 'detail';
$lang[31] = 'Your subscription is active';
$lang[32] = 'Click on the <b>Update Credit Card</b> button to update your payment source';
$lang[33] = 'subscribe';
$lang[34] = 'Currently there are no active subscriptions - try again later';
$lang[35] = 'Active';
$lang[36] = 'Trialing';
$lang[37] = 'Past Due';
$lang[38] = 'Canceled';
$lang[39] = 'plan name';
$lang[40] = 'status';
$lang[41] = 'price';
$lang[42] = 'update';
$lang[43] = 'cancel';
$lang[44] = 'Current Subscription:';
$lang[45] = 'New Subscription:';
$lang[46] = 'Including credit from your existing subscription, payment for the new subscription would be due in:';
$lang[47] = 'change subscription';
$lang[48] = 'Free';
$lang[49] = 'Payment History';
$lang[50] = 'Enter the amount you would like to pay:';
$lang[51] = 'Save Price';
$lang[52] = '(minimum 1.00)';
$lang[53] = 'Start Subscription';
$lang[54] = 'Update Credit Card';
$lang[55] = 'You have entered an invalid amount';
$lang[56] = 'The minimum allowed amount is %1';
