<?php
/**
 * Jamroom Group Discussions module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'Discussion';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Discussions';
$lang[2]  = 'Create New Discussion';
$lang[3]  = 'Title';
$lang[4]  = 'Enter a title for this discussion';
$lang[5]  = 'An error was encountered creating the discussion - please try again.';
$lang[6]  = 'Invalid id - please pass in a valid discussion id.';
$lang[7]  = 'The discussion entry was not found in the datastore - please try again.';
$lang[8]  = 'update discussion';
$lang[9]  = 'update';
$lang[10] = 'Discussion';
$lang[11] = 'Created a new discussion';
$lang[12] = 'Updated a discussion';
$lang[13] = 'category';
$lang[14] = 'Enter a discussion category';
$lang[15] = 'description';
$lang[16] = 'Describe this discussion';
$lang[17] = 'Associated Group';
$lang[18] = 'Optionally select a Group for this discussion to be associated with';
$lang[19] = 'Comments';
$lang[20] = 'Discussion Forum';
$lang[21] = 'View All';
$lang[22] = 'started';
$lang[23] = 'replies';
$lang[24] = 'Follow this Discussion';
$lang[25] = 'Success - you are now following this discussion';
$lang[26] = 'You are no longer following this discussion';
$lang[27] = 'Discussion Updated';
$lang[28] = 'If you are following a Group Discussion, how do you want to be notified?';
$lang[29] = 'Discussion Notification';
$lang[30] = 'Success - you are now following this group';
$lang[31] = 'You are no longer following this group';
$lang[32] = 'Group Watch';
$lang[33] = 'When you are watching a group for new discussionss how do you want to be notified?';
$lang[34] = 'started';
$lang[35] = 'replies';
