<?php
/**
 * Jamroom Video module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!

// Profile Menu Entry Name
$lang['menu'] = 'video';

// Keys
$lang[1]  = 'play';
$lang[2]  = 'pause';
$lang[3]  = 'stop';
$lang[4]  = 'mute';
$lang[5]  = 'unmute';
$lang[6]  = 'max volume';
$lang[7]  = 'repeat';
$lang[8]  = 'repeat off';
$lang[9]  = 'create';
$lang[10] = 'title';
$lang[11] = 'Enter a title for the video file - this will be shown your profile.';
$lang[12] = 'category';
$lang[13] = 'If you have already entered genres in other video files, you may select any previous genre, or enter a new genre in text field';
$lang[14] = 'video file';
$lang[15] = 'select and upload the video file.';
$lang[16] = 'cover image';
$lang[17] = 'if you would like to associate an image file with this song, upload it here.';
$lang[18] = 'An error was encountered creating the video file - please try again.';
$lang[19] = 'The video file was successfully created!';
$lang[20] = 'Invalid id - please pass in a valid video id.';
$lang[21] = 'The video entry was not found in the datastore - please try again.';
$lang[22] = 'create video file';
$lang[23] = 'update video file';
$lang[24] = 'update';
$lang[25] = 'The video file was successfully updated!';
$lang[26] = 'video length';
$lang[27] = 'video bitrate';
$lang[28] = 'video sample rate';
$lang[29] = 'upload a new video file';
$lang[30] = 'upload a new video image';
$lang[31] = 'album';
$lang[32] = 'If this video file is part of an album, enter the album name here.';
$lang[33] = 'Posted a new Video File';
$lang[34] = 'Albums';
$lang[35] = 'Video';
$lang[36] = 'Video Genres';
$lang[37] = 'streams';
$lang[38] = 'This video file is currently being processed and will appear here when complete.';
$lang[39] = 'videos';
$lang[40] = 'insert video';
$lang[41] = 'no videos were found';
$lang[42] = 'album';
$lang[43] = 'If this video file is part of an album, enter the album name here.';
$lang[44] = 'Albums';
$lang[45] = 'create album';
$lang[46] = 'album video files';
$lang[47] = 'Select all the video files that belong to this album - they will be saved individually so they can be edited.';
$lang[48] = 'select video files';
$lang[49] = 'select cover image';
$lang[50] = 'purchase';
$lang[51] = 'Updated a Video';
$lang[52] = 'delete album';
$lang[53] = 'Are you sure you want to delete this album?';
$lang[54] = 'next';
$lang[55] = 'full screen';
$lang[56] = 'restore screen';
$lang[57] = 'shuffle';
$lang[58] = 'shuffle off';
$lang[59] = 'previous';
$lang[60] = 'You forgot to upload a video file';
$lang[61] = 'Created a new Video Album';
$lang[62] = 'Updated a Video Album';
$lang[63] = 'Upload Video';
$lang[64] = 'video title';
$lang[65] = 'Created a new Video';
