<?php
/**
 * Jamroom jrElastic2 skin
 *
 * copyright 2018 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * Jamroom Elastic 2 Skin - lang strings
 * @copyright 2003 - 2017 by The Jamroom Network - All Rights Reserved
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Home';
$lang[2]  = 'create';
$lang[3]  = 'account';
$lang[4]  = 'Top 10 Tracks';
$lang[5]  = 'Logout';
$lang[6]  = 'Forum Topics';
$lang[7]  = 'Welcome To Elastic';
$lang[8]  = 'New Members';
$lang[9]  = 'by';
$lang[10] = 'Upcoming Events';
$lang[11] = 'Latest Gallery Images';
$lang[12] = 'Highly Configurable';
$lang[13] = 'Responsive Design';
$lang[14] = 'Site Builder';
$lang[15] = 'Template Editor';
$lang[16] = 'ACP';
$lang[17] = 'dashboard';
$lang[18] = 'Scalable';
$lang[19] = 'Expandable';
$lang[20] = 'Updates';
$lang[21] = 'Birthday';
$lang[22] = "login";
$lang[23] = "Update Cover Image";
$lang[24] = 'Search';
$lang[25] = 'Account Settings';
$lang[26] = 'Hot Videos';
$lang[27] = "Help";
$lang[28] = "Documentation";
$lang[29] = "Community Forum";
$lang[30] = "VIP Support";
$lang[31] = "Marketplace";
$lang[32] = "User Chat";
$lang[33] = "View Skin Demo";
$lang[34] = "Skin Language";
$lang[35] = "skin settings";
$lang[36] = "skin notes";
$lang[37] = "skin images";
$lang[38] = "skin style";
$lang[39] = "skin templates";
$lang[40] = 'Forum Topics';
$lang[41] = 'Hot Videos';
$lang[42] = 'Admin Blog';
$lang[43] = 'Followers';
$lang[44] = 'About';
$lang[45] = 'Profile Stats';
$lang[46] = 'Recently Rated';
$lang[47] = 'Influences';
$lang[48] = 'Latest Comments';
$lang[49] = "users";
$lang[50] = "quota browser";
$lang[51] = "profile browser";
$lang[52] = "user accounts";
$lang[53] = "users online";
$lang[54] = "image caches";
$lang[55] = "ACP";
$lang[56] = "system tools";
$lang[57] = "activity logs";
$lang[58] = "reset image caches";
$lang[59] = "integrity check";
$lang[60] = "system updates";
$lang[61] = "system check";
$lang[62] = "Follow";
$lang[63] = "Bio";
$lang[64] = "more";
$lang[65] = "Joined";
$lang[66] = "Edit";
$lang[67] = 'Cart';
$lang[68] = 'Following';
$lang[69] = 'Click to see full image';
$lang[70] = 'View Profile';
$lang[71] = 'Watch Video';
$lang[72] = 'View Gallery';
$lang[73] = 'user name or email';
$lang[74] = 'password';
$lang[75] = 'remember me';
