<?php
/**
 * Jamroom Playlists module
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'playlist';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Created a new Playlist';
$lang[2]  = 'add to playlist';
$lang[3]  = 'remove from playlist';
$lang[4]  = 'remove this item from the playlist?';
$lang[5]  = "Update Playlist";
$lang[6]  = 'playlist title';
$lang[7]  = 'Enter a title for your playlist';
$lang[8]  = 'Unable to retrieve playlist from the database - please try again';
$lang[9]  = 'Playlist';
$lang[10] = 'Tracks';
$lang[11] = 'Title';
$lang[12] = 'Genre';
$lang[13] = 'Album';
$lang[14] = 'Playlist Rating';
$lang[15] = 'add to existing playlist';
$lang[16] = 'add';
$lang[17] = 'new playlist name';
$lang[18] = 'create';
$lang[19] = 'close';
$lang[20] = 'Updated a Playlist';
$lang[21] = 'Playlists';
$lang[22] = 'previous';
$lang[23] = 'play';
$lang[24] = 'pause';
$lang[25] = 'next';
$lang[26] = 'stop';
$lang[27] = 'mute';
$lang[28] = 'unmute';
$lang[29] = 'max volume';
$lang[30] = 'full screen';
$lang[31] = 'restore screen';
$lang[32] = 'shuffle';
$lang[33] = 'shuffle off';
$lang[34] = 'repeat';
$lang[35] = 'repeat off';
$lang[36] = 'Update Required';
$lang[37] = 'Standalone Playlist';
$lang[38] = 'Playlist Options';
$lang[39] = 'Playlists';
$lang[40] = 'Title';
$lang[41] = 'items';
$lang[42] = 'Insert';
$lang[43] = 'You have not created any playlists yet.';
$lang[44] = 'This playlist is empty and no longer exists';
$lang[45] = 'Log In';
$lang[46] = 'Create New Account';
$lang[47] = 'Log in or Create your account to save this playlist!';
$lang[48] = 'You must be logged in to create a Playlist!';
$lang[49] = 'Click here to Login or Create an Account';
$lang[50] = 'Successfully added to playlist';
$lang[51] = 'You haven\'t created any <b>Playlists</b> yet';
$lang[52] = 'You can build collections of audio files you like into a playlist. <br>Visit other profiles who have uploaded audio and use the';
$lang[53] = 'button to create playlists.<br>Playlists you create will show here on your profile.';
