<?php
/**
 * Jamroom Documentation module
 *
 * copyright 2018 The Jamroom Network
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'documentation';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Create Document';
$lang[2]  = 'title';
$lang[3]  = 'Enter a title for this new document';
$lang[4]  = 'category';
$lang[5]  = 'Enter a category for this new document';
$lang[6]  = 'Update Document';
$lang[7]  = 'Indent Level';
$lang[8]  = 'What Indent Level should this document title be shown in the index listing?';
$lang[9]  = 'Show Table of Contents';
$lang[10] = 'If the Show Table of Contents option is checked, a Table of Contents will be shown at the top of a document when the number of sections in the document exceeds 3.';
$lang[11] = 'An error was encountered creating the new document - please try again';
$lang[12] = 'create new section';
$lang[13] = 'save changes';
$lang[14] = 'Enter a title for this section - it will be used in the Table of Contents. If left empty, this section will not generate a link in the Table of Contents if one is created for this document.';
$lang[15] = 'text';
$lang[16] = 'enter the text for this text section';
$lang[17] = 'image';
$lang[18] = 'select the image you would like to upload';
$lang[19] = 'select image';
$lang[20] = 'Floated Left';
$lang[21] = 'Floated Right';
$lang[22] = 'image location';
$lang[23] = 'select the location you would like this image to appear in relation to the text';
$lang[24] = 'image size';
$lang[25] = 'select the size of image you would like to show in the text';
$lang[26] = 'screenshot';
$lang[27] = 'select and upload the screenshot you would like to appear in this section.';
$lang[28] = 'image caption';
$lang[29] = 'enter a caption for this image (optional)';
$lang[30] = 'file';
$lang[31] = 'select and upload a file you would like to appear as a download in this section.';
$lang[32] = 'select file';
$lang[33] = 'file information';
$lang[34] = 'enter detailed information about this file (optional)';
$lang[35] = 'code';
$lang[36] = 'enter the code for this code block.';
$lang[37] = 'syntax highlighting';
$lang[38] = 'select the language that is being used in the code box, and the result will be syntax highlighted.';
$lang[39] = 'function name';
$lang[40] = 'This is the name of the function';
$lang[41] = 'function description';
$lang[42] = 'Details about what this function is used for.';
$lang[43] = 'function return';
$lang[44] = 'What data type does this function return?';
$lang[45] = 'parameter';
$lang[46] = 'type';
$lang[47] = 'default';
$lang[48] = 'required';
$lang[49] = 'description';
$lang[50] = 'Select the type of document section you wish to add';
$lang[51] = 'download file';
$lang[52] = 'Function';
$lang[53] = 'Documentation';
$lang[54] = 'Table of Contents';
$lang[55] = 'YouTube ID or URL';
$lang[56] = 'Enter the ID or URL for the youtube video - the YouTube ID is the 11 character ID found in the youtube URL. Alternatively you can just enter the full URL and the ID will be extracted from it. ';
$lang[57] = 'Optional Description';
$lang[58] = 'Enter a description that will be displayed beneath the youtube video';
$lang[59] = 'add new section';
$lang[60] = 'show parameter list';
$lang[61] = 'If this is checked, then a parameter list will be shown below the function name in the output.';
$lang[62] = 'There were no documents found that matched your search term';
$lang[63] = 'Search Results';
$lang[64] = 'Chapters';
$lang[65] = 'viewable by';
$lang[66] = 'If you would like to restrict this document to only being viewable by specific User Groups or Quotas, select them here.';
$lang[67] = 'more than 1 group allowed';
$lang[68] = 'Profile Owners';
$lang[69] = '(group) All Users (including logged out)';
$lang[70] = '(group) Logged In Users';
$lang[71] = '(group) Logged Out Users';
$lang[72] = 'Show Related Documents';
$lang[73] = 'If this option is checked, keywords in this document will be linked to related documents';
$lang[74] = 'Image URL';
$lang[75] = 'Enter a URL to link to the image. If left empty, the image will display in a lightbox when clicked.';
$lang[76] = 'Related Documents:';
