<?php
/**
 * Jamroom Invitations module
 *
 * copyright 2017 The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'invite';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Invitations';
$lang[2]  = 'Create New Invitation';
$lang[3]  = 'You have received no invitations';
$lang[4]  = 'Email Invitations';
$lang[5]  = 'Received';
$lang[6]  = 'Invitations Received';
$lang[7]  = 'Your Invitations';
$lang[8]  = 'update invitation';
$lang[9]  = 'update';
$lang[10] = 'Invitation';
$lang[11] = 'Created a new invitation';
$lang[12] = 'Updated an invitation';
$lang[13] = 'Your Invitations';
$lang[14] = 'Invitation Text';
$lang[15] = 'Enter the invitation text that will be emailed to the recipient';
$lang[16] = 'Item Type';
$lang[17] = 'Select the item type you want to invite users to';
$lang[18] = 'Item Title';
$lang[19] = 'Select the item you want to invite users to (options available after type is selected above)';
$lang[20] = 'No invitations found - click on the &quotNew Invitation&quot; button to create one.';
$lang[21] = 'New Invitation';
$lang[22] = 'Updated';
$lang[23] = 'Invite Text';
$lang[24] = 'Item';
$lang[25] = 'Update';
$lang[26] = 'Delete';
$lang[27] = 'Are you sure you want to delete this invitation?';
$lang[28] = 'Users have already been sent this invitation - Please be sure that you want to update it';
$lang[29] = 'invitations';
$lang[30] = 'Invite Users';
$lang[31] = 'There are no users for you to invite';
$lang[32] = 'Select Users to Invite';
$lang[33] = 'Select users to invite';
$lang[34] = '(multiple selections allowed)';
$lang[35] = 'Selected Item Type is not active';
$lang[36] = 'Are you sure you want to invite the selected recipients?';
$lang[37] = 'Please be patient while the invitations are sent';
$lang[38] = 'Invitation sent to';
$lang[39] = 'more';
$lang[40] = 'You do not have an invitation to the item';
$lang[41] = 'Thank You for responding to this invitation from';
$lang[42] = 'Invited Users';
$lang[43] = 'User invitations sent';
$lang[44] = 'Invalid users submitted';
$lang[45] = 'Email invitations sent';
$lang[46] = 'If you receive an invitation, would you like to be notified?';
$lang[47] = 'Visit this profile';
$lang[48] = 'One per line';
$lang[49] = 'Enter the email addresses (one per line) for the users you would like to invite';
$lang[50] = 'Your Profile';
$lang[51] = 'Viewed';
$lang[52] = 'Sender';
$lang[53] = 'View';
$lang[54] = 'Invitation Sent';
$lang[55] = '- View All Users -';
